/*
 * Copyright 2026 Sriram (Sriram-Codes-SW)
 *
 * This file is part of Doorprints.
 *
 * Doorprints is free software: you can redistribute it and/or modify it under the terms of the GNU Affero General
 * Public License as published by the Free Software Foundation, version 3 of the License.
 *
 * Doorprints is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied
 * warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Affero General Public License for more
 * details.
 *
 * You should have received a copy of the GNU Affero General Public License along with Doorprints (the file LICENSE;
 * the file NOTICE has additional permissions under section 7). If not, see <https://www.gnu.org/licenses/>.
 *
 * SPDX-License-Identifier: AGPL-3.0-only
 */

package app.doorprints.shared.ai

// Generated by .github/scripts/parity-vectors-kotlin.py from docs/ai/evals/parity-vectors.json; do not edit.

/** The shared AI test vectors, as text, for the common tests (see [ParityVectorsTest]). */
internal val PARITY_VECTORS_JSON: String = listOf(
    """{
  "redact" : [ {
    "method" : "place",
    "name" : "Mr. Ramesh Kumar",
    "phone" : "+91 98450 12345",
    "input" : "C/o Ramesh Kumar, 12 MG Road",
    "expected" : "C/o [contact], 12 MG Road"
  }, {
    "method" : "place",
    "name" : "Mr. Ramesh Kumar",
    "phone" : "+91 98450 12345",
    "input" : "C/o Ramesh  Kumar",
    "expected" : "C/o [contact]"
  }, {
    "method" : "place",
    "name" : "Mr. Ramesh Kumar",
    "phone" : "+91 98450 12345",
    "input" : "C/O RAMESH KUMAR",
    "expected" : "C/O [contact]"
  }, {
    "method" : "place",
    "name" : "Mr. Ramesh Kumar",
    "phone" : "+91 98450 12345",
    "input" : "C/o Kumar Ramesh, 12 MG Road",
    "expected" : "C/o [contact], 12 MG Road"
  }, {
    "method" : "place",
    "name" : "Mr. Ramesh Kumar",
    "phone" : "+91 98450 12345",
    "input" : "C/o Ramesh.Kumar",
    "expected" : "C/o [contact]"
  }, {
    "method" : "place",
    "name" : "Mr. Ramesh Kumar",
    "phone" : "+91 98450 12345",
    "input" : "Kumar Park",
    "expected" : "Kumar Park"
  }, {
    "method" : "place",
    "name" : "Mr. Ramesh Kumar",
    "phone" : "+91 98450 12345",
    "input" : "Ramesh Nagar",
    "expected" : "Ramesh Nagar"
  }, {
    "method" : "place",
    "name" : "Mr. Ramesh Kumar",
    "phone" : "+91 98450 12345",
    "input" : "Ramesh Layout",
    "expected" : "Ramesh Layout"
  }, {
    "method" : "place",
    "name" : "Mr. Ramesh Kumar",
    "phone" : "+91 98450 12345",
    "input" : "Ramesh Kumaran Road",
    "expected" : "Ramesh Kumaran Road"
  }, {
    "method" : "place",
    "name" : "Mr. Ramesh Kumar",
    "phone" : "+91 98450 12345",
    "input" : "Mr. Ramesh Kumar's gate, Kumar Park",
    "expected" : "[contact]'s gate, Kumar Park"
  }, {
    "method" : "place",
    "name" : "Mr. Ramesh Kumar",
    "phone" : "+91 98450 12345",
    "input" : "Flat 1203, tower 9",
    "expected" : "Flat 1203, tower 9"
  }, {
    "method" : "place",
    "name" : "Mr. Ramesh Kumar",
    "phone" : "+91 98450 12345",
    "input" : "Plot 12/4, 3rd cross, 560038",
    "expected" : "Plot 12/4, 3rd cross, 560038"
  }, {
    "method" : "freeText",
    "name" : "Mr. Ramesh Kumar",
    "phone" : "+91 98450 12345",
    "input" : "Ramesh's 2BHK, Indiranagar",
    "expected" : "[contact]'s 2BHK, Indiranagar"
  }, {
    "method" : "freeText",
    "name" : "Mr. Ramesh Kumar",
    "phone" : "+91 98450 12345",
    "input" : "Mr. Ramesh Kumar's flat, call 98450-12345",
    "expected" : "[contact]'s flat, call [phone]"
  }, {
    "method" : "freeText",
    "name" : "Mr. Ramesh Kumar",
    "phone" : "+91 98450 12345",
    "input" : "Ramesh said the owner lives upstairs; Kumar uncle is the broker. Rameshwaram trip",
    "expected" : "[contact] said the owner lives upstairs; [contact] uncle is the broker. Rameshwaram trip"
  }, {
    "method" : "freeText",
    "name" : "Mr. Ramesh Kumar",
    "phone" : "+91 98450 12345",
    "input" : "RAMESH ok with pets",
    "expected" : "[contact] ok with pets"
  }, {
    "method" : "freeText",
    "name" : "Mr. Ramesh Kumar",
    "phone" : "+91 98450 12345",
    "input" : "Rameshwaram view",
    "expected" : "Rameshwaram view"
  }, {
    "method" : "freeText",
    "name" : "Mr. Ramesh Kumar",
    "phone" : "+91 98450 12345",
    "input" : "https://example.com/rent/ramesh-2bhk",
    "expected" : "https://example.com/rent/[contact]-2bhk"
  }, {
    "method" : "freeText",
    "name" : "Mr. Ramesh Kumar",
    "phone" : "+91 98450 12345",
    "input" : "Deposit 75000, maintenance 3500",
    "expected" : "Deposit 75000, maintenance 3500"
  }, {
    "method" : "freeText",
    "name" : "Mr. Ramesh Kumar",
    "phone" : "+91 98450 12345",
    "input" : "Price 2500000 negotiable",
    "expected" : "Price 2500000 negotiable"
  }, {
    "method" : "freeText",
    "name" : "Mr. Ramesh Kumar",
    "phone" : "+91 98450 12345",
    "input" : "Rs 1,20,00,000",
    "expected" : "Rs 1,20,00,000"
  }, {
    "method" : "freeText",
    "name" : "Mr. Ramesh Kumar",
    "phone" : "+91 98450 12345",
    "input" : "Visited on 2026-09-22 10:30",
    "expected" : "Visited on 2026-09-22 10:30"
  }, {
    "method" : "freeText",
    "name" : "Mr. Ramesh Kumar",
    "phone" : "+91 98450 12345",
    "input" : "22-09-2026 at 5 pm",
    "expected" : "22-09-2026 at 5 pm"
  }, {
    "method" : "freeText",
    "name" : "Mr. Ramesh Kumar",
    "phone" : "+91 98450 12345",
    "input" : "1650 sqft, 3 BHK, 2 cars",
    "expected" : "1650 sqft, 3 BHK, 2 cars"
  }, {
    "method" : "freeText",
    "name" : "Mr. Ramesh Kumar",
    "phone" : "+91 98450 12345",
    "input" : "call +91-98450-12345 after 6",
    "expected" : "call [phone] after 6"
  }, {
    "method" : "freeText",
    "name" : "Mr. Ramesh Kumar",
    "phone" : "+91 98450 12345",
    "input" : "call 00919845012345",
    "expected" : "call [phone]"
  }, {
    "method" : "freeText",
    "name" : "Mr. Ramesh Kumar",
    "phone" : "+91 98450 12345",
    "input" : "call 098450-12345",
    "expected" : "call [phone]"
  }, {
    "method" : "freeText",
    "name" : "Mr. Ramesh Kumar",
    "phone" : "+91 98450 12345",
    "input" : "landline 080-2345 6789 only",
    "expected" : "landline [phone] only"
  }, {
    "method" : "freeText",
    "name" : "Mr. Ramesh Kumar",
    "phone" : "+91 98450 12345",
    "input" : "landline 2345-6789 only",
    "expected" : "landline 2345-6789 only"
  }, {
    "method" : "freeText",
    "name" : "Mr. Ramesh Kumar",
    "phone" : "+91 98450 12345",
    "input" : "UK +44 20 7946 0958",
    "expected" : "UK [phone]"
  }, {
    "method" : "freeText",
    "name" : "Mr. Ramesh Kumar",
    "phone" : "+91 98450 12345",
    "input" : "7760012345 other number",
    "expected" : "[phone] other number"
  }, {
    "method" : "freeText",
    "name" : "Mr. Ramesh Kumar",
    "phone" : "+91 98450 12345",
    "input" : "Deposit 2345678",
    "expected" : "Deposit 2345678"
  }, {
    "method" : "freeText",
    "name" : "Mr. Ramesh Kumar",
    "phone" : "+91 98450 12345",
    "input" : "nothing to hide",
    "expected" : "nothing to hide"
  }, {
    "method" : "place",
    "name" : "K. Ramesh",
    "phone" : null,
    "input" : "C/o K Ramesh, 3rd Cross",
    "expected" : "C/o [contact], 3rd Cross"
  }, {
    "method" : "place",
    "name" : "K. Ramesh",
    "phone" : null,
    "input" : "C/o K. Ramesh",
    "expected" : "C/o [contact]"
  }, {
    "method" : "place",
    "name" : "K. Ramesh",
    "phone" : null,
    "input" : "C/o K.Ramesh",
    "expected" : "C/o [contact]"
  }, {
    "method" : "place",
    "name" : "K. Ramesh",
    "phone" : null,
    "input" : "Ramesh K, Anna Nagar",
    "expected" : "[contact], Anna Nagar"
  }, {
    "method" : "place",
    "name" : "K. Ramesh",
    "phone" : null,
    "input" : "Ramesh Layout, C/o K Ramesh",
    "expected" : "Ramesh Layout, C/o [contact]"
  }, {
    "method" : "place",
    "name" : "K. Ramesh",
    "phone" : null,
    "input" : "c/o k ramesh",
    "expected" : "c/o [contact]"
  }, {
    "method" : "place",
    "name" : "K. Ramesh",
    "phone" : null,
    "input" : "Ramesh flat",
    "expected" : "Ramesh flat"
  }, {
    "method" : "place",
    "name" : "A. K. Sharma",
    "phone" : null,
    "input" : "C/o A K Sharma",
    "expected" : "C/o [contact]"
  }, {
    "method" : "place",
    "name" : "A. K. Sharma",
    "phone" : null,
    "input" : "C/o AK Sharma",
    "expected" : "C/o [contact]"
  }, {
    "method" : "place",
    "name" : "A. K. Sharma",
    "phone" : null,
    "input" : "C/o A. K. Sharma",
    "expected" : "C/o [contact]"
  }, {
    "method" : "place",
    "name" : "A. K. Sharma",
    "phone" : null,
    "input" : "C/o A.K.Sharma",
    "expected" : "C/o [contact]"
  }, {
    "method" : "place",
    "name" : "A. K. Sharma",
    "phone" : null,
    "input" : "Sharma A K, 12 MG Road",
    "expected" : "[contact], 12 MG Road"
  }, {
    "method" : "place",
    "name" : "A. K. Sharma",
    "phone" : null,
    "input" : "Sharma Nagar",
    "expected" : "Sharma Nagar"
  }, {
    "method" : "freeText",
    "name" : "रमेश",
    "phone" : null,
    "input" : "रमेश जी से बात हुई",
    "expected" : "[contact] जी से बात हुई"
  }, {
    "method" : "freeText",
    "name" : "ரமேஷ்",
    "phone" : null,
    "input" : "ரமேஷ் அழைத்தார்",
    "expected" : "[contact] அழைத்தார்"
  }, {
    "method" : "freeText",
    "name" : "KR",
    "phone" : "12",
    "input" : "KR Puram flat",
    "expected" : "[contact] Puram flat"
  }, {
    "method" : "freeText",
    "name" : null,
    "phone" : "123456",
    "input" : "Price 123456 Rs",
    "expected" : "Price 123456 Rs"
  }, {
    "method" : "scrub",
    "name" : "Mr. Ramesh Kumar",
    "phone" : "+91 98450 12345",
    "input" : "House: Blue gate\nLocality: Indiranagar\nContact: Ramesh Kumar\nNotes: Ramesh is helpful, +91 98450 12345",
    "expected" : "House: Blue gate\nLocality: Indiranagar\nNotes: [contact] is helpful, [phone]"
  }, {
    "method" : "scrub",
    "name" : null,
    "phone" : null,
    "input" : "Contact: X\nNotes: fine",
    "expected" : "Notes: fine"
  }, {
    "method" : "generic",
    "name" : "Mr. Ramesh Kumar",
    "phone" : "+91 98450 12345",
    "input" : "call 9845012345 or 080 23456789, flat 1203",
    "expected" : "call [phone] or [phone], flat 1203"
  }, {
    "method" : "freeText",
    "name" : "Suresh Rao",
    "phone" : null,
    "input" : "Mail suresh.rao@gmail.com or sureshrao1983@yahoo.co.in, insta @suresh_rao, https://wa.me/919886055555",
    "expected" : "Mail [email] or [email], insta @[contact], https://wa.me/[phone]"
  }, {
    "method" : "freeText",
    "name" : "Suresh Rao",
    "phone" : "+91 98860 55555",
    "input" : "Mail sureshrao1983@yahoo.co.in",
    "expected" : "Mail [email]"
  }, {
    "method" : "freeText",
    "name" : "Anil Verma",
    "phone" : null,
    "input" : "Portal https://portal.example/contact?email=suresh.rao@gmail.com&ref=1",
    "expected" : "Portal https://portal.example/contact?email=[email]&ref=1"
  }, {
    "method" : "freeText",
    "name" : "Anil Verma",
    "phone" : null,
    "input" : "Call 98450 12345 or mail anil@example.com",
    "expected" : "Call [phone] or mail [email]"
  }, {
    "method" : "freeText",
    "name" : "Anil Verma",
    "phone" : null,
    "input" : "98450 12345,anil@example.com",
    "expected" : "[phone],[email]"
  }, {
    "method" : "freeText",
    "name" : "Anil Verma",
    "phone" : null,
    "input" : "Mail me at sam@example.com.",
    "expected" : "Mail me at [email]."
  }, {
    "method" : "place",
    "name" : "Anil Verma",
    "phone" : null,
    "input" : "Shop 4, mail owner@example.org",
    "expected" : "Shop 4, mail [email]"
  }, {
    "method" : "scrub",
    "name" : "Suresh Rao",
    "phone" : null,
    "input" : "Contact: Suresh Rao\nmail suresh@gmail.com ok",
    "expected" : "mail [email] ok"
  }, {
    "method" : "generic",
    "name" : null,
    "phone" : null,
    "input" : "Write to a.b@c.in or 98450 12345, see https://example.com/l/123",
    "expected" : "Write to [email] or [phone], see https://example.com/l/123"
  }, {
    "method" : "freeText",
    "name" : null,
    "phone" : null,
    "input" : "Rent 28k @ month, ask x@y or a@b.",
    "expected" : "Rent 28k @ month, ask x@y or a@b."
  }, {
    "method" : "freeText",
    "name" : "Rose Bush",
    "phone" : null,
    "input" : "Rose garden at the back, a bush hedge, Rose said keys with Rosemary",
    "expected" : "[contact] garden at the back, a [contact] hedge, [contact] said keys with Rosemary"
  }, {
    "method" : "freeText",
    "name" : "Will Mark",
    "phone" : null,
    "input" : "Owner will mark the parking spot; Will Mark called",
    "expected" : "Owner [contact] the parking spot; [contact] called"
  }, {
    "method" : "freeText",
    "name" : "Gold",
    "phone" : null,
    "input" : "Gold coloured gate",
    "expected" : "[contact] coloured gate"
  }, {
    "method" : "freeText",
    "name" : "Ram",
    "phone" : null,
    "input" : "Ram Nagar, Sri Ram Temple road, ramp access",
    "expected" : "[contact] Nagar, Sri [contact] Temple road, ramp access"
  }, {
    "method" : "place",
    "name" : "Rose Bush",
    "phone" : null,
    "input" : "Rose Bush Lane, Rosewood Park",
    "expected" : "[contact] Lane, Rosewood Park"
  }, {
    "method" : "freeText",
    "name" : "K. Ramesh",
    "phone" : null,
    "input" : "K block near K R Puram",
    "expected" : "K block near K R Puram"
  }, {
    "method" : "freeText",
    "name" : null,
    "phone" : null,
    "input" : "Mail ravi+flat3@example.co.in now",
    "expected" : "Mail [email] now"
  }, {
    "method" : "freeText",
    "name" : null,
    "phone" : null,
    "input" : "Mail aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa@example.com now",
    "expected" : "Mail [email] now"
  }, {
    "method" : "generic",
    "name" : null,
    "phone" : null,
    "input" : "Call +91 98200 12345 now",
    "expected" : "Call [phone] now"
  }, {
    "method" : "generic",
    "name" : null,
    "phone" : null,
    "input" : "Call 098200 12345 now",
    "expected" : "Call [phone] now"
  }, {
    "method" : "generic",
    "name" : null,
    "phone" : null,
    "input" : "Call 98200-12345",
    "expected" : "Call [phone]"
  }, {
    "method" : "generic",
    "name" : null,
    "phone" : null,
    "input" : "Call 98200.12345.",
    "expected" : "Call [phone]."
  }, {
    "method" : "generic",
    "name" : null,
    "phone" : null,
    "input" : "Call 98200 12345 / 98200 12346",
    "expected" : "Call [phone] / [phone]"
  }, {
    "method" : "generic",
    "name" : null,
    "phone" : null,
    "input" : "Call 9820012345",
    "expected" : "Call [phone]"
  }, {
    "method" : "generic",
    "name" : null,
    "phone" : null,
    "input" : "Call +91-98200-12345",
    "expected" : "Call [phone]"
  }, {
    "method" : "generic",
    "name" : null,
    "phone" : null,
    "input" : "Call +91 (98200) 12345",
    "expected" : "Call [phone]"
  }, {
    "method" : "generic",
    "name" : null,
    "phone" : null,
    "input" : "Call 91 98200 12345",
    "expected" : "Call [phone]"
  }, {
    "method" : "generic",
    "name" : null,
    "phone" : null,
    "input" : "Call 0091 98200 12345",
    "expected" : "Call 0091 [phone]"
  }, {
    "method" : "generic",
    "name" : null,
    "phone" : null,
    "input" : "Office 011-4155 0101",
    "expected" : "Office [phone]"
  }, {
    "method" : "generic",
    "name" : null,
    "phone" : null,
    "input" : "Office 022 2655 0101",
    "expected" : "Office [phone]"
  }, {
    "method" : "generic",
    "name" : null,
    "phone" : null,
    "input" : "Office 033 2359 0101",
    "expected" : "Office [phone]"
  }, {
    "method" : "generic",
    "name" : null,
    "phone" : null,
    "input" : "Office 040-2354 0000",
    "expected" : "Office [phone]"
  }, {
    "method" : "generic",
    "name" : null,
    "phone" : null,
    "input" : "Office 044 2434 5555",
    "expected" : "Office [phone]"
  }, {
    "method" : "generic",
    "name" : null,
""",
    """    "phone" : null,
    "input" : "Office 0484 235 1234",
    "expected" : "Office [phone]"
  }, {
    "method" : "generic",
    "name" : null,
    "phone" : null,
    "input" : "Office 0361 245 5555",
    "expected" : "Office [phone]"
  }, {
    "method" : "generic",
    "name" : null,
    "phone" : null,
    "input" : "Office 0172-270 0000",
    "expected" : "Office [phone]"
  }, {
    "method" : "generic",
    "name" : null,
    "phone" : null,
    "input" : "Office 0135 274 1234",
    "expected" : "Office [phone]"
  }, {
    "method" : "generic",
    "name" : null,
    "phone" : null,
    "input" : "Office 0177-265 1234",
    "expected" : "Office [phone]"
  }, {
    "method" : "generic",
    "name" : null,
    "phone" : null,
    "input" : "Office 01141550101",
    "expected" : "Office [phone]"
  }, {
    "method" : "generic",
    "name" : null,
    "phone" : null,
    "input" : "Office (022) 2655 0101",
    "expected" : "Office [phone]"
  }, {
    "method" : "generic",
    "name" : null,
    "phone" : null,
    "input" : "Office (080) 23456789",
    "expected" : "Office [phone]"
  }, {
    "method" : "generic",
    "name" : null,
    "phone" : null,
    "input" : "Office +91-22-2655 0101",
    "expected" : "Office [phone]"
  }, {
    "method" : "generic",
    "name" : null,
    "phone" : null,
    "input" : "Office 079-2630 1234 / 079-2630 1235",
    "expected" : "Office [phone] / [phone]"
  }, {
    "method" : "generic",
    "name" : null,
    "phone" : null,
    "input" : "Bandra West, Mumbai 400050, flat 1203",
    "expected" : "Bandra West, Mumbai 400050, flat 1203"
  }, {
    "method" : "generic",
    "name" : null,
    "phone" : null,
    "input" : "Rent Rs 85,000/-, deposit Rs 5,10,000",
    "expected" : "Rent Rs 85,000/-, deposit Rs 5,10,000"
  }, {
    "method" : "generic",
    "name" : null,
    "phone" : null,
    "input" : "Price Rs 12,34,567 only",
    "expected" : "Price Rs 12,34,567 only"
  }, {
    "method" : "generic",
    "name" : null,
    "phone" : null,
    "input" : "Plot 4/12, Sector 56, Gurugram 122011",
    "expected" : "Plot 4/12, Sector 56, Gurugram 122011"
  }, {
    "method" : "generic",
    "name" : null,
    "phone" : null,
    "input" : "1.2 lakh per month, 1800 sq ft, 3rd floor",
    "expected" : "1.2 lakh per month, 1800 sq ft, 3rd floor"
  }, {
    "method" : "generic",
    "name" : null,
    "phone" : null,
    "input" : "Visit on 08-10-2026 at 5 pm",
    "expected" : "Visit on 08-10-2026 at 5 pm"
  }, {
    "method" : "generic",
    "name" : null,
    "phone" : null,
    "input" : "Pincode 682030, Kochi",
    "expected" : "Pincode 682030, Kochi"
  }, {
    "method" : "generic",
    "name" : null,
    "phone" : null,
    "input" : "Rent 28000 deposit 280000",
    "expected" : "Rent 28000 deposit 280000"
  }, {
    "method" : "generic",
    "name" : null,
    "phone" : null,
    "input" : "هاتف ٩٨٢٠٠ ١٢٣٤٥",
    "expected" : "هاتف [phone]",
    "note" : "Arabic-Indic digits"
  }, {
    "method" : "generic",
    "name" : null,
    "phone" : null,
    "input" : "فون ۹۸۲۰۰ ۱۲۳۴۵",
    "expected" : "فون [phone]",
    "note" : "Extended Arabic-Indic digits"
  }, {
    "method" : "generic",
    "name" : null,
    "phone" : null,
    "input" : "फोन ९८२०० १२३४५",
    "expected" : "फोन [phone]",
    "note" : "Devanagari digits"
  }, {
    "method" : "generic",
    "name" : null,
    "phone" : null,
    "input" : "ফোন ৯৮২০০ ১২৩৪৫",
    "expected" : "ফোন [phone]",
    "note" : "Bengali digits"
  }, {
    "method" : "generic",
    "name" : null,
    "phone" : null,
    "input" : "ਫ਼ੋਨ ੯੮੨੦੦ ੧੨੩੪੫",
    "expected" : "ਫ਼ੋਨ [phone]",
    "note" : "Gurmukhi digits"
  }, {
    "method" : "generic",
    "name" : null,
    "phone" : null,
    "input" : "ફોન ૯૮૨૦૦ ૧૨૩૪૫",
    "expected" : "ફોન [phone]",
    "note" : "Gujarati digits"
  }, {
    "method" : "generic",
    "name" : null,
    "phone" : null,
    "input" : "ଫୋନ ୯୮୨୦୦ ୧୨୩୪୫",
    "expected" : "ଫୋନ [phone]",
    "note" : "Odia digits"
  }, {
    "method" : "generic",
    "name" : null,
    "phone" : null,
    "input" : "தொலைபேசி ௯௮௨௦௦ ௧௨௩௪௫",
    "expected" : "தொலைபேசி [phone]",
    "note" : "Tamil digits"
  }, {
    "method" : "generic",
    "name" : null,
    "phone" : null,
    "input" : "ఫోన్ ౯౮౨౦౦ ౧౨౩౪౫",
    "expected" : "ఫోన్ [phone]",
    "note" : "Telugu digits"
  }, {
    "method" : "generic",
    "name" : null,
    "phone" : null,
    "input" : "ಫೋನ್ ೯೮೨೦೦ ೧೨೩೪೫",
    "expected" : "ಫೋನ್ [phone]",
    "note" : "Kannada digits"
  }, {
    "method" : "generic",
    "name" : null,
    "phone" : null,
    "input" : "ഫോൺ ൯൮൨൦൦ ൧൨൩൪൫",
    "expected" : "ഫോൺ [phone]",
    "note" : "Malayalam digits"
  }, {
    "method" : "generic",
    "name" : null,
    "phone" : null,
    "input" : "ऑफिस ०११-४१५५ ०१०१",
    "expected" : "ऑफिस [phone]",
    "note" : "Devanagari digits, a Delhi landline"
  }, {
    "method" : "generic",
    "name" : null,
    "phone" : null,
    "input" : "+91 ९८२०० 12345",
    "expected" : "[phone]",
    "note" : "Latin and Devanagari digits in one number"
  }, {
    "method" : "generic",
    "name" : null,
    "phone" : null,
    "input" : "किराया ८५,००० रुपये, फ्लैट १२०३",
    "expected" : "किराया ८५,००० रुपये, फ्लैट १२०३",
    "note" : "a price and a door number in Devanagari digits are not a phone"
  }, {
    "method" : "generic",
    "name" : null,
    "phone" : null,
    "input" : "ফ্ল্যাট ১২০৩, পিন ৭০০০৩৩",
    "expected" : "ফ্ল্যাট ১২০৩, পিন ৭০০০৩৩",
    "note" : "a door number and a PIN code in Bengali digits are not a phone"
  }, {
    "method" : "freeText",
    "name" : "Pravin Kulkarni",
    "phone" : "98900 55555",
    "input" : "फोन ९८९०० ५५५५५",
    "expected" : "फोन [phone]",
    "note" : "the saved number written in Devanagari digits"
  }, {
    "method" : "place",
    "name" : null,
    "phone" : null,
    "input" : "Plot 4, ফোন ৯৮২০০ ১২৩৪৫",
    "expected" : "Plot 4, ফোন [phone]",
    "note" : "a place field with a phone in Bengali digits"
  }, {
    "method" : "freeText",
    "name" : "Hiren Patel",
    "phone" : "+91 98250 12345",
    "input" : "Hiren bhai 98250-12345 / 079-2630 1234",
    "expected" : "[contact] bhai [phone] / [phone]"
  }, {
    "method" : "freeText",
    "name" : "Pravin Kulkarni",
    "phone" : "98900 55555",
    "input" : "प्रवीण जी: Pravin Kulkarni 9890055555",
    "expected" : "प्रवीण जी: [contact] [phone]"
  }, {
    "method" : "freeText",
    "name" : null,
    "phone" : "080 2345 6789",
    "input" : "call 080-2345-6789 or +91 80 2345 6789",
    "expected" : "call [phone] or +91 [phone]"
  }, {
    "method" : "freeText",
    "name" : null,
    "phone" : "080 2345 6789",
    "input" : "reach the office on 2345 6789",
    "expected" : "reach the office on 2345 6789",
    "knownGap" : "S4b-BL-174a",
    "wanted" : "reach the office on [phone]"
  }, {
    "method" : "generic",
    "name" : null,
    "phone" : null,
    "input" : "फोन ९८२०० १२३४५, mail anil@example.com",
    "expected" : "फोन [phone], mail [email]",
    "note" : "a phone in Devanagari digits beside an email address"
  }, {
    "method" : "freeText",
    "name" : "Anil Verma",
    "phone" : null,
    "input" : "९८२०० १२३४५,anil@example.com",
    "expected" : "[phone],[email]",
    "note" : "Devanagari digits then an address, no space between"
  }, {
    "method" : "generic",
    "name" : null,
    "phone" : null,
    "input" : "९८२००१२३४५@example.com",
    "expected" : "[phone]@example.com",
    "note" : "the number goes before the email rule runs, as for 9820012345@example.com below"
  }, {
    "method" : "generic",
    "name" : null,
    "phone" : null,
    "input" : "9820012345@example.com",
    "expected" : "[phone]@example.com",
    "note" : "the Latin-digit twin of the case above"
  }, {
    "method" : "freeText",
    "name" : "Pravin Kulkarni",
    "phone" : "98900 55555",
    "input" : "९८९०० ५५५५५ pravin@example.com",
    "expected" : "[phone] [email]",
    "note" : "the saved number in Devanagari digits, then an address that holds a name part"
  }, {
    "method" : "generic",
    "name" : null,
    "phone" : null,
    "input" : "Office (022) 2655 0101,ravi@b.in",
    "expected" : "Office [phone],[email]",
    "note" : "a parenthesised STD code beside an email address"
  }, {
    "method" : "generic",
    "name" : null,
    "phone" : null,
    "input" : "Call (0484) 235 1234 or office1234567890@x.in",
    "expected" : "Call [phone] or [email]",
    "note" : "ten digits inside an email local part are not a phone"
  }, {
    "method" : "generic",
    "name" : null,
    "phone" : null,
    "input" : "Mail रमेश९८२००१२३४५@example.com now",
    "expected" : "Mail [email] now",
    "note" : "native digits inside an email local part go with the address"
  }, {
    "method" : "freeText",
    "name" : null,
    "phone" : "1234 5678",
    "input" : "Call १२३४ ५६७८ now",
    "expected" : "Call [phone] now",
    "note" : "a saved 8-digit number written in Devanagari digits: only the saved-number rule can see it, the phone-like rule needs 10"
  } ],
  "sanitize" : [ {
    "raw" : {
      "label" : "2BHK near Indiranagar",
      "locality" : "Indiranagar",
      "street" : "100 Feet Road",
      "price" : "25,000",
      "priceType" : "rent",
      "bedrooms" : "2BHK",
      "contactName" : "Ramesh",
      "contactPhone" : "+91 98450 12345",
      "listingUrl" : "https://example.com/l/123",
      "notes" : "Deposit 1.5 lakh.",
      "amenities" : [ "Parking", "Lift", "parking" ]
    },
    "source" : "2BHK for rent in Indiranagar, 100 Feet Road. Rent 25,000, deposit 1.5 lakh. Call Ramesh 98450 12345. https://example.com/l/123 Parking, lift.",
    "expected" : {
      "label" : "2BHK near Indiranagar",
      "address" : null,
      "street" : "100 Feet Road",
      "locality" : "Indiranagar",
      "price" : 25000,
      "priceType" : "RENT",
      "bedrooms" : 2,
      "contactName" : "Ramesh",
      "contactPhone" : "+91 98450 12345",
      "listingUrl" : "https://example.com/l/123",
      "notes" : "Deposit 1.5 lakh.",
      "amenities" : [ "parking", "lift" ],
      "warnings" : [ ]
    }
  }, {
    "raw" : {
      "price" : "1.2 Cr",
      "priceType" : "SALE",
      "bedrooms" : "studio",
      "contactPhone" : "99999 88888",
      "listingUrl" : "https://evil.example.com"
    },
    "source" : "2BHK for rent in Indiranagar, 100 Feet Road. Rent 25,000, deposit 1.5 lakh. Call Ramesh 98450 12345. https://example.com/l/123 Parking, lift.",
    "expected" : {
      "label" : "Studio",
      "address" : null,
      "street" : null,
      "locality" : null,
      "price" : 12000000,
      "priceType" : "SALE",
      "bedrooms" : 0,
      "contactName" : null,
      "contactPhone" : null,
      "listingUrl" : null,
      "notes" : null,
      "amenities" : [ ],
      "warnings" : [ "contactPhone: not found in the listing text, dropped", "listingUrl: not found in the listing text, dropped", "label: generated because the model returned none" ]
    }
  }, {
    "raw" : {
      "price" : "85 lakh",
      "priceType" : "lease",
      "bedrooms" : "25",
      "locality" : "  ",
      "notes" : "null"
    },
    "source" : "flat for sale 85 lakh",
    "expected" : {
      "label" : "House",
      "address" : null,
      "street" : null,
      "locality" : null,
      "price" : 8500000,
      "priceType" : "RENT",
      "bedrooms" : null,
      "contactName" : null,
      "contactPhone" : null,
      "listingUrl" : null,
      "notes" : null,
      "amenities" : [ ],
      "warnings" : [ "bedrooms: 25 is out of range, dropped", "label: generated because the model returned none" ]
    }
  }, {
    "raw" : {
      "price" : "call for price",
      "priceType" : "swap",
      "bedrooms" : "many",
      "listingUrl" : "ftp://x.example.com/a"
    },
    "source" : "ftp://x.example.com/a",
    "expected" : {
      "label" : "House",
      "address" : null,
      "street" : null,
      "locality" : null,
      "price" : null,
      "priceType" : null,
      "bedrooms" : null,
      "contactName" : null,
      "contactPhone" : null,
      "listingUrl" : null,
      "notes" : null,
      "amenities" : [ ],
      "warnings" : [ "priceType: 'swap' is not RENT or SALE, dropped", "price: could not read 'call for price', dropped", "bedrooms: could not read 'many', dropped", "listingUrl: only http(s) links are allowed, dropped", "label: generated because the model returned none" ]
    }
  }, {
    "raw" : {
      "price" : "25k",
      "bedrooms" : "3",
      "label" : null,
      "street" : "MG Road"
    },
    "source" : "25k MG Road",
    "expected" : {
      "label" : "3BHK in MG Road",
      "address" : null,
      "street" : "MG Road",
      "locality" : null,
      "price" : 25000,
      "priceType" : null,
      "bedrooms" : 3,
      "contactName" : null,
      "contactPhone" : null,
      "listingUrl" : null,
      "notes" : null,
      "amenities" : [ ],
      "warnings" : [ "label: generated because the model returned none" ]
    }
  }, {
    "raw" : {
      "price" : "12.75 k",
      "priceType" : "MONTHLY",
      "label" : "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
    },
    "source" : "",
    "expected" : {
      "label" : "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
      "address" : null,
      "street" : null,
      "locality" : null,
      "price" : 12750,
      "priceType" : "RENT",
      "bedrooms" : null,
      "contactName" : null,
      "contactPhone" : null,
      "listingUrl" : null,
      "notes" : null,
      "amenities" : [ ],
      "warnings" : [ "label: truncated to 200 characters" ]
    }
  }, {
    "raw" : {
      "amenities" : [ "A0", "A1", "A2", "A3", "A4", "A5", "A6", "A7", "A8", "A9", "A10", "A11", "A12", "A13", "A14", "A15", "A16", "A17", "A18", "A19", "A20", "A21", "A22", "A23", "A24" ]
    },
    "source" : "",
    "expected" : {
      "label" : "House",
      "address" : null,
      "street" : null,
      "locality" : null,
      "price" : null,
      "priceType" : null,
      "bedrooms" : null,
      "contactName" : null,
      "contactPhone" : null,
      "listingUrl" : null,
      "notes" : null,
      "amenities" : [ "a0", "a1", "a2", "a3", "a4", "a5", "a6", "a7", "a8", "a9", "a10", "a11", "a12", "a13", "a14", "a15", "a16", "a17", "a18", "a19" ],
      "warnings" : [ "amenities: kept the first 20", "label: generated because the model returned none" ]
    }
  }, {
    "raw" : null,
    "source" : "anything",
    "expected" : {
      "label" : "Untitled listing",
      "address" : null,
      "street" : null,
      "locality" : null,
      "price" : null,
      "priceType" : null,
      "bedrooms" : null,
""",
    """      "contactName" : null,
      "contactPhone" : null,
      "listingUrl" : null,
      "notes" : null,
      "amenities" : [ ],
      "warnings" : [ "Model returned nothing usable" ]
    }
  }, {
    "raw" : {
      "label" : "1BHK furnished flat, Bandra West",
      "locality" : "Bandra West",
      "price" : "Rs 85,000/-",
      "priceType" : "RENT",
      "bedrooms" : "1 BHK",
      "contactName" : "Amit",
      "contactPhone" : "98200 12345",
      "listingUrl" : null,
      "notes" : "Deposit 6 months. Carpet 520 sq ft. Bachelors not allowed.",
      "amenities" : [ "Furnished" ]
    },
    "source" : "FOR RENT: 1 BHK FULLY FURNISHED FLAT AT BANDRA WEST NEAR LINKING ROAD. RENT Rs 85,000/- PER MONTH. DEPOSIT 6 MONTHS. 520 SQ FT CARPET. BACHELORS NOT ALLOWED. CALL NOW 98200 12345 - AMIT",
    "expected" : {
      "label" : "1BHK furnished flat, Bandra West",
      "address" : null,
      "street" : null,
      "locality" : "Bandra West",
      "price" : 85000,
      "priceType" : "RENT",
      "bedrooms" : 1,
      "contactName" : "Amit",
      "contactPhone" : "98200 12345",
      "listingUrl" : null,
      "notes" : "Deposit 6 months. Carpet 520 sq ft. Bachelors not allowed.",
      "amenities" : [ "furnished" ],
      "warnings" : [ ]
    }
  }, {
    "raw" : {
      "locality" : "Sector 56",
      "price" : "65k",
      "priceType" : "rent",
      "bedrooms" : "3BHK",
      "contactPhone" : "+91 99100 12345"
    },
    "source" : "Gurgaon Sector 56 mein 3BHK flat kiraye pe hai. Rent 65k mahina, deposit 2 mahine ka. Phone 99100 12345.",
    "expected" : {
      "label" : "3BHK in Sector 56",
      "address" : null,
      "street" : null,
      "locality" : "Sector 56",
      "price" : 65000,
      "priceType" : "RENT",
      "bedrooms" : 3,
      "contactName" : null,
      "contactPhone" : "+91 99100 12345",
      "listingUrl" : null,
      "notes" : null,
      "amenities" : [ ],
      "warnings" : [ "label: generated because the model returned none" ]
    }
  }, {
    "raw" : {
      "label" : "4BHK kothi, Gomti Nagar",
      "price" : "1.2 lakh/month",
      "priceType" : "RENTAL",
      "bedrooms" : "4"
    },
    "source" : "4BHK independent kothi for rent at Gomti Nagar, Lucknow. Rent 1.2 lakh/month. DM for details.",
    "expected" : {
      "label" : "4BHK kothi, Gomti Nagar",
      "address" : null,
      "street" : null,
      "locality" : null,
      "price" : 120000,
      "priceType" : "RENT",
      "bedrooms" : 4,
      "contactName" : null,
      "contactPhone" : null,
      "listingUrl" : null,
      "notes" : null,
      "amenities" : [ ],
      "warnings" : [ ]
    }
  }, {
    "raw" : {
      "label" : "2BHK in Baner",
      "price" : "Rs. 85 lakhs",
      "priceType" : "resale",
      "bedrooms" : "2 BHK",
      "contactPhone" : "98900 55555"
    },
    "source" : "Baner, Pune - 2 BHK flat for sale. Rs. 85 lakhs (negotiable). Sampark: Pravin 98900 55555.",
    "expected" : {
      "label" : "2BHK in Baner",
      "address" : null,
      "street" : null,
      "locality" : null,
      "price" : 8500000,
      "priceType" : "SALE",
      "bedrooms" : 2,
      "contactName" : null,
      "contactPhone" : "98900 55555",
      "listingUrl" : null,
      "notes" : null,
      "amenities" : [ ],
      "warnings" : [ ]
    }
  }, {
    "raw" : {
      "label" : "3BHK house, Sanjauli",
      "price" : "₹ 95 L",
      "priceType" : "SALE",
      "bedrooms" : "3BHK"
    },
    "source" : "FOR SALE: 3BHK house with garden, Sanjauli, Shimla. Asking ₹ 95 L. Owner not sharing phone.",
    "expected" : {
      "label" : "3BHK house, Sanjauli",
      "address" : null,
      "street" : null,
      "locality" : null,
      "price" : 9500000,
      "priceType" : "SALE",
      "bedrooms" : 3,
      "contactName" : null,
      "contactPhone" : null,
      "listingUrl" : null,
      "notes" : null,
      "amenities" : [ ],
      "warnings" : [ ]
    }
  }, {
    "raw" : {
      "label" : "Beltola duplex",
      "price" : "1.5 Cr fixed",
      "priceType" : "SALE",
      "bedrooms" : "3",
      "listingUrl" : "https://example.com/ghy/beltola-duplex"
    },
    "source" : "FOR SALE: 3BHK duplex, Beltola, Guwahati. Price 1.5 Cr fixed. Details: https://example.com/ghy/beltola-duplex",
    "expected" : {
      "label" : "Beltola duplex",
      "address" : null,
      "street" : null,
      "locality" : null,
      "price" : 15000000,
      "priceType" : "SALE",
      "bedrooms" : 3,
      "contactName" : null,
      "contactPhone" : null,
      "listingUrl" : "https://example.com/ghy/beltola-duplex",
      "notes" : null,
      "amenities" : [ ],
      "warnings" : [ ]
    }
  }, {
    "raw" : {
      "label" : "Salt Lake 4BHK",
      "price" : "₹1,25,000",
      "priceType" : "RENT",
      "bedrooms" : "4 BHK"
    },
    "source" : "Salt Lake flat to let, ₹1,25,000 per month for a big 4BHK.",
    "expected" : {
      "label" : "Salt Lake 4BHK",
      "address" : null,
      "street" : null,
      "locality" : null,
      "price" : 125000,
      "priceType" : "RENT",
      "bedrooms" : 4,
      "contactName" : null,
      "contactPhone" : null,
      "listingUrl" : null,
      "notes" : null,
      "amenities" : [ ],
      "warnings" : [ ]
    }
  }, {
    "raw" : {
      "label" : "Banjara Hills villa",
      "price" : "Rs 12,34,567",
      "priceType" : "SALE"
    },
    "source" : "Villa at Banjara Hills for Rs 12,34,567 only.",
    "expected" : {
      "label" : "Banjara Hills villa",
      "address" : null,
      "street" : null,
      "locality" : null,
      "price" : 1234567,
      "priceType" : "SALE",
      "bedrooms" : null,
      "contactName" : null,
      "contactPhone" : null,
      "listingUrl" : null,
      "notes" : null,
      "amenities" : [ ],
      "warnings" : [ ]
    }
  }, {
    "raw" : {
      "label" : "Banjara Hills villa",
      "price" : "Rs 4.5 Cr",
      "priceType" : "SALE",
      "contactPhone" : "90000 12345"
    },
    "source" : "Banjara Hills villa, Rs 4.5 Cr, call 90000 12345",
    "expected" : {
      "label" : "Banjara Hills villa",
      "address" : null,
      "street" : null,
      "locality" : null,
      "price" : 45000000,
      "priceType" : "SALE",
      "bedrooms" : null,
      "contactName" : null,
      "contactPhone" : "90000 12345",
      "listingUrl" : null,
      "notes" : null,
      "amenities" : [ ],
      "warnings" : [ ]
    }
  }, {
    "raw" : {
      "label" : "Ballygunge 2BHK",
      "price" : "Price on request",
      "priceType" : "SALE",
      "bedrooms" : "2BHK",
      "contactName" : "Banerjee",
      "contactPhone" : "033 2464 5555"
    },
    "source" : "Ballygunge Phari 2BHK for sale, 1100 sq ft. Price on request, call for the rate. Mr. Banerjee 033-2464 5555.",
    "expected" : {
      "label" : "Ballygunge 2BHK",
      "address" : null,
      "street" : null,
      "locality" : null,
      "price" : null,
      "priceType" : "SALE",
      "bedrooms" : 2,
      "contactName" : "Banerjee",
      "contactPhone" : "033 2464 5555",
      "listingUrl" : null,
      "notes" : null,
      "amenities" : [ ],
      "warnings" : [ "price: could not read 'Price on request', dropped" ]
    }
  }, {
    "raw" : {
      "label" : "Salt Lake flat",
      "contactName" : "Dipankar Dutta",
      "contactPhone" : "033 2359 0101"
    },
    "source" : "Dipankar Dutta - 033-2359-0101",
    "expected" : {
      "label" : "Salt Lake flat",
      "address" : null,
      "street" : null,
      "locality" : null,
      "price" : null,
      "priceType" : null,
      "bedrooms" : null,
      "contactName" : "Dipankar Dutta",
      "contactPhone" : "033 2359 0101",
      "listingUrl" : null,
      "notes" : null,
      "amenities" : [ ],
      "warnings" : [ ]
    }
  }, {
    "raw" : {
      "label" : "Powai 2BHK",
      "contactPhone" : "+91 98200 12345"
    },
    "source" : "Powai 2BHK in Hiranandani. Message me. 98200 12346",
    "expected" : {
      "label" : "Powai 2BHK",
      "address" : null,
      "street" : null,
      "locality" : null,
      "price" : null,
      "priceType" : null,
      "bedrooms" : null,
      "contactName" : null,
      "contactPhone" : null,
      "listingUrl" : null,
      "notes" : null,
      "amenities" : [ ],
      "warnings" : [ "contactPhone: not found in the listing text, dropped" ]
    }
  }, {
    "raw" : {
      "locality" : "Rajpur Road",
      "bedrooms" : "2.5 BHK"
    },
    "source" : "Rajpur Road, Dehradun: 2.5 BHK flat for rent.",
    "expected" : {
      "label" : "2BHK in Rajpur Road",
      "address" : null,
      "street" : null,
      "locality" : "Rajpur Road",
      "price" : null,
      "priceType" : null,
      "bedrooms" : 2,
      "contactName" : null,
      "contactPhone" : null,
      "listingUrl" : null,
      "notes" : null,
      "amenities" : [ ],
      "warnings" : [ "label: generated because the model returned none" ]
    }
  }, {
    "raw" : {
      "locality" : "Velachery",
      "price" : "₹9,500",
      "bedrooms" : "1RK"
    },
    "source" : "Velachery 1RK ₹9,500 only.",
    "expected" : {
      "label" : "Studio in Velachery",
      "address" : null,
      "street" : null,
      "locality" : "Velachery",
      "price" : 9500,
      "priceType" : null,
      "bedrooms" : 0,
      "contactName" : null,
      "contactPhone" : null,
      "listingUrl" : null,
      "notes" : null,
      "amenities" : [ ],
      "warnings" : [ "label: generated because the model returned none" ]
    }
  }, {
    "raw" : {
      "locality" : "Candolim",
      "bedrooms" : "4+1 BHK"
    },
    "source" : "4+1 BHK villa for sale in Candolim",
    "expected" : {
      "label" : "4BHK in Candolim",
      "address" : null,
      "street" : null,
      "locality" : "Candolim",
      "price" : null,
      "priceType" : null,
      "bedrooms" : 4,
      "contactName" : null,
      "contactPhone" : null,
      "listingUrl" : null,
      "notes" : null,
      "amenities" : [ ],
      "warnings" : [ "label: generated because the model returned none" ]
    }
  }, {
    "raw" : {
      "label" : "Jaipur 2BHK",
      "locality" : "मालवीय नगर (Malviya Nagar)",
      "price" : "22,000",
      "priceType" : "RENT",
      "notes" : "सिक्योरिटी 2 महीने",
      "amenities" : [ "Lift", "LIFT", "lift ", "लिफ्ट" ]
    },
    "source" : "Jaipur flat. किराया ₹22,000 प्रति माह.",
    "expected" : {
      "label" : "Jaipur 2BHK",
      "address" : null,
      "street" : null,
      "locality" : "मालवीय नगर (Malviya Nagar)",
      "price" : 22000,
      "priceType" : "RENT",
      "bedrooms" : null,
      "contactName" : null,
      "contactPhone" : null,
      "listingUrl" : null,
      "notes" : "सिक्योरिटी 2 महीने",
      "amenities" : [ "lift", "लिफ्ट" ],
      "warnings" : [ ]
    }
  } ],
  "snippet" : [ {
    "doc" : "House: Blue gate\nLocality: Indiranagar\nPrice: Rs 25000 per month (rent)\nNotes: close to the metro, good water",
    "question" : "Which house is close to the metro?",
    "expected" : "Notes: close to the metro, good water"
  }, {
    "doc" : "House: A\nLocality: B",
    "question" : "zzz",
    "expected" : "House: A"
  }, {
    "doc" : "House: long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long ",
    "question" : "long house",
    "expected" : "House: long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long lo…"
  } ],
  "inlineIds" : [ {
    "input" : "See [house:11111111-1111-4111-8111-111111111111] and [house: 22222222-2222-4222-8222-222222222222, house:33333333-3333-4333-8333-333333333333].",
    "expected" : [ "11111111-1111-4111-8111-111111111111", "22222222-2222-4222-8222-222222222222", "33333333-3333-4333-8333-333333333333" ]
  }, {
    "input" : "[HOUSE:11111111-1111-4111-8111-111111111111] twice [house:11111111-1111-4111-8111-111111111111]",
    "expected" : [ "11111111-1111-4111-8111-111111111111" ]
  }, {
    "input" : "none here",
    "expected" : [ ]
  }, {
    "input" : "[house:not-a-uuid]",
    "expected" : [ ]
  } ],
  "route" : {
    "start" : [ 12.9716, 77.5946 ],
    "points" : [ [ "a", 12.975, 77.6 ], [ "b", 12.97, 77.59 ], [ "c", 12.98, 77.61 ], [ "d", 12.9716, 77.5946 ] ],
    "nearestNeighbour" : [ {
      "id" : "d",
      "meters" : 0,
      "walkMinutes" : 0
    }, {
      "id" : "b",
      "meters" : 529,
      "walkMinutes" : 9
    }, {
      "id" : "a",
      "meters" : 1218,
      "walkMinutes" : 20
    }, {
      "id" : "c",
      "meters" : 1218,
      "walkMinutes" : 20
    } ],
    "inOrder" : [ {
      "id" : "a",
      "meters" : 697,
      "walkMinutes" : 12
    }, {
      "id" : "b",
      "meters" : 1218,
      "walkMinutes" : 20
    }, {
      "id" : "c",
      "meters" : 2436,
      "walkMinutes" : 40
    }, {
      "id" : "d",
      "meters" : 1912,
      "walkMinutes" : 32
    } ]
  },
  "inTheRunning" : [ {
    "status" : "NEW",
    "expected" : true
  }, {
    "status" : "SHORTLISTED",
    "expected" : true
  }, {
    "status" : "REJECTED",
    "expected" : false
  }, {
    "status" : "TAKEN",
    "expected" : true
  }, {
    "status" : "NOT_CHOSEN",
    "expected" : false
  } ],
  "schemaDialect" : [ {
    "name" : "listing",
    "gemini" : {
      "type" : "object",
      "properties" : {
        "label" : {
          "type" : "string",
          "description" : "Short human label, e.g. '2BHK near Indiranagar metro'",
          "nullable" : true
        },
        "address" : {
          "type" : "string",
          "description" : "Full postal address as written in the listing",
          "nullable" : true
        },
        "street" : {
          "type" : "string",
          "description" : "Street / road name only",
          "nullable" : true
        },
        "locality" : {
          "type" : "string",
          "description" : "Locality / neighbourhood / area",
          "nullable" : true
        },
        "price" : {
          "type" : "string",
          "description" : "Monthly rent or sale price in rupees exactly as written, e.g. '25,000' or '1.2 Cr'",
          "nullable" : true
        },
        "priceType" : {
          "type" : "string",
          "description" : "RENT or SALE",
          "nullable" : true
        },
        "bedrooms" : {
          "type" : "string",
          "description" : "Number of bedrooms, e.g. '2' for 2BHK",
          "nullable" : true
        },
        "contactName" : {
          "type" : "string",
          "description" : "Contact person name",
          "nullable" : true
        },
""",
    """        "contactPhone" : {
          "type" : "string",
          "description" : "Contact phone number exactly as written",
          "nullable" : true
        },
        "listingUrl" : {
          "type" : "string",
          "description" : "Listing URL if one is present in the text",
          "nullable" : true
        },
        "notes" : {
          "type" : "string",
          "description" : "Other useful facts (deposit, floor, furnishing, availability) in one short paragraph",
          "nullable" : true
        },
        "amenities" : {
          "type" : "array",
          "description" : "Amenities such as parking, lift, power backup, gym",
          "items" : {
            "type" : "string"
          }
        }
      }
    },
    "strict" : {
      "type" : "object",
      "properties" : {
        "label" : {
          "type" : [ "string", "null" ],
          "description" : "Short human label, e.g. '2BHK near Indiranagar metro'"
        },
        "address" : {
          "type" : [ "string", "null" ],
          "description" : "Full postal address as written in the listing"
        },
        "street" : {
          "type" : [ "string", "null" ],
          "description" : "Street / road name only"
        },
        "locality" : {
          "type" : [ "string", "null" ],
          "description" : "Locality / neighbourhood / area"
        },
        "price" : {
          "type" : [ "string", "null" ],
          "description" : "Monthly rent or sale price in rupees exactly as written, e.g. '25,000' or '1.2 Cr'"
        },
        "priceType" : {
          "type" : [ "string", "null" ],
          "description" : "RENT or SALE"
        },
        "bedrooms" : {
          "type" : [ "string", "null" ],
          "description" : "Number of bedrooms, e.g. '2' for 2BHK"
        },
        "contactName" : {
          "type" : [ "string", "null" ],
          "description" : "Contact person name"
        },
        "contactPhone" : {
          "type" : [ "string", "null" ],
          "description" : "Contact phone number exactly as written"
        },
        "listingUrl" : {
          "type" : [ "string", "null" ],
          "description" : "Listing URL if one is present in the text"
        },
        "notes" : {
          "type" : [ "string", "null" ],
          "description" : "Other useful facts (deposit, floor, furnishing, availability) in one short paragraph"
        },
        "amenities" : {
          "type" : "array",
          "description" : "Amenities such as parking, lift, power backup, gym",
          "items" : {
            "type" : "string"
          }
        }
      },
      "required" : [ "label", "address", "street", "locality", "price", "priceType", "bedrooms", "contactName", "contactPhone", "listingUrl", "notes", "amenities" ],
      "additionalProperties" : false
    },
    "trailer" : "Reply with only a JSON object of this shape: {\"type\":\"object\",\"properties\":{\"label\":{\"type\":[\"string\",\"null\"],\"description\":\"Short human label, e.g. '2BHK near Indiranagar metro'\"},\"address\":{\"type\":[\"string\",\"null\"],\"description\":\"Full postal address as written in the listing\"},\"street\":{\"type\":[\"string\",\"null\"],\"description\":\"Street / road name only\"},\"locality\":{\"type\":[\"string\",\"null\"],\"description\":\"Locality / neighbourhood / area\"},\"price\":{\"type\":[\"string\",\"null\"],\"description\":\"Monthly rent or sale price in rupees exactly as written, e.g. '25,000' or '1.2 Cr'\"},\"priceType\":{\"type\":[\"string\",\"null\"],\"description\":\"RENT or SALE\"},\"bedrooms\":{\"type\":[\"string\",\"null\"],\"description\":\"Number of bedrooms, e.g. '2' for 2BHK\"},\"contactName\":{\"type\":[\"string\",\"null\"],\"description\":\"Contact person name\"},\"contactPhone\":{\"type\":[\"string\",\"null\"],\"description\":\"Contact phone number exactly as written\"},\"listingUrl\":{\"type\":[\"string\",\"null\"],\"description\":\"Listing URL if one is present in the text\"},\"notes\":{\"type\":[\"string\",\"null\"],\"description\":\"Other useful facts (deposit, floor, furnishing, availability) in one short paragraph\"},\"amenities\":{\"type\":\"array\",\"description\":\"Amenities such as parking, lift, power backup, gym\",\"items\":{\"type\":\"string\"}}},\"required\":[\"label\",\"address\",\"street\",\"locality\",\"price\",\"priceType\",\"bedrooms\",\"contactName\",\"contactPhone\",\"listingUrl\",\"notes\",\"amenities\"],\"additionalProperties\":false}"
  }, {
    "name" : "answer",
    "gemini" : {
      "type" : "object",
      "properties" : {
        "answer" : {
          "type" : "string",
          "description" : "The answer, in 1-6 sentences, citing houses inline as [house:<id>]"
        },
        "citedHouseIds" : {
          "type" : "array",
          "description" : "Ids of the houses cited inline as [house:<id>] in the answer, copied exactly from the context",
          "items" : {
            "type" : "string"
          }
        }
      },
      "required" : [ "answer" ]
    },
    "strict" : {
      "type" : "object",
      "properties" : {
        "answer" : {
          "type" : "string",
          "description" : "The answer, in 1-6 sentences, citing houses inline as [house:<id>]"
        },
        "citedHouseIds" : {
          "type" : "array",
          "description" : "Ids of the houses cited inline as [house:<id>] in the answer, copied exactly from the context",
          "items" : {
            "type" : "string"
          }
        }
      },
      "required" : [ "answer", "citedHouseIds" ],
      "additionalProperties" : false
    },
    "trailer" : "Reply with only a JSON object of this shape: {\"type\":\"object\",\"properties\":{\"answer\":{\"type\":\"string\",\"description\":\"The answer, in 1-6 sentences, citing houses inline as [house:<id>]\"},\"citedHouseIds\":{\"type\":\"array\",\"description\":\"Ids of the houses cited inline as [house:<id>] in the answer, copied exactly from the context\",\"items\":{\"type\":\"string\"}}},\"required\":[\"answer\",\"citedHouseIds\"],\"additionalProperties\":false}"
  }, {
    "name" : "plan",
    "gemini" : {
      "type" : "object",
      "properties" : {
        "summary" : {
          "type" : "string",
          "description" : "2-4 sentences explaining the plan"
        },
        "stops" : {
          "type" : "array",
          "description" : "Houses to visit, in visiting order",
          "items" : {
            "type" : "object",
            "properties" : {
              "houseId" : {
                "type" : "string",
                "description" : "House id exactly as returned by a tool"
              },
              "reason" : {
                "type" : "string",
                "description" : "Why this house is in the plan, one sentence"
              }
            }
          }
        }
      }
    },
    "strict" : {
      "type" : "object",
      "properties" : {
        "summary" : {
          "type" : "string",
          "description" : "2-4 sentences explaining the plan"
        },
        "stops" : {
          "type" : "array",
          "description" : "Houses to visit, in visiting order",
          "items" : {
            "type" : "object",
            "properties" : {
              "houseId" : {
                "type" : "string",
                "description" : "House id exactly as returned by a tool"
              },
              "reason" : {
                "type" : "string",
                "description" : "Why this house is in the plan, one sentence"
              }
            },
            "required" : [ "houseId", "reason" ],
            "additionalProperties" : false
          }
        }
      },
      "required" : [ "summary", "stops" ],
      "additionalProperties" : false
    },
    "trailer" : "Reply with only a JSON object of this shape: {\"type\":\"object\",\"properties\":{\"summary\":{\"type\":\"string\",\"description\":\"2-4 sentences explaining the plan\"},\"stops\":{\"type\":\"array\",\"description\":\"Houses to visit, in visiting order\",\"items\":{\"type\":\"object\",\"properties\":{\"houseId\":{\"type\":\"string\",\"description\":\"House id exactly as returned by a tool\"},\"reason\":{\"type\":\"string\",\"description\":\"Why this house is in the plan, one sentence\"}},\"required\":[\"houseId\",\"reason\"],\"additionalProperties\":false}}},\"required\":[\"summary\",\"stops\"],\"additionalProperties\":false}"
  } ],
  "openaiRequest" : [ {
    "call" : "listing",
    "tier" : 1,
    "model" : "test-model",
    "system" : "You extract house listings.",
    "user" : "Two bedroom flat in Indiranagar, rent 25,000.",
    "temperature" : 0,
    "expected" : {
      "model" : "test-model",
      "temperature" : 0,
      "max_tokens" : 2048,
      "messages" : [ {
        "role" : "system",
        "content" : "You extract house listings."
      }, {
        "role" : "user",
        "content" : "Two bedroom flat in Indiranagar, rent 25,000."
      } ],
      "response_format" : {
        "type" : "json_schema",
        "json_schema" : {
          "name" : "listing",
          "strict" : true,
          "schema" : {
            "type" : "object",
            "properties" : {
              "label" : {
                "type" : [ "string", "null" ],
                "description" : "Short human label, e.g. '2BHK near Indiranagar metro'"
              },
              "address" : {
                "type" : [ "string", "null" ],
                "description" : "Full postal address as written in the listing"
              },
              "street" : {
                "type" : [ "string", "null" ],
                "description" : "Street / road name only"
              },
              "locality" : {
                "type" : [ "string", "null" ],
                "description" : "Locality / neighbourhood / area"
              },
              "price" : {
                "type" : [ "string", "null" ],
                "description" : "Monthly rent or sale price in rupees exactly as written, e.g. '25,000' or '1.2 Cr'"
              },
              "priceType" : {
                "type" : [ "string", "null" ],
                "description" : "RENT or SALE"
              },
              "bedrooms" : {
                "type" : [ "string", "null" ],
                "description" : "Number of bedrooms, e.g. '2' for 2BHK"
              },
              "contactName" : {
                "type" : [ "string", "null" ],
                "description" : "Contact person name"
              },
              "contactPhone" : {
                "type" : [ "string", "null" ],
                "description" : "Contact phone number exactly as written"
              },
              "listingUrl" : {
                "type" : [ "string", "null" ],
                "description" : "Listing URL if one is present in the text"
              },
              "notes" : {
                "type" : [ "string", "null" ],
                "description" : "Other useful facts (deposit, floor, furnishing, availability) in one short paragraph"
              },
              "amenities" : {
                "type" : "array",
                "description" : "Amenities such as parking, lift, power backup, gym",
                "items" : {
                  "type" : "string"
                }
              }
            },
            "required" : [ "label", "address", "street", "locality", "price", "priceType", "bedrooms", "contactName", "contactPhone", "listingUrl", "notes", "amenities" ],
            "additionalProperties" : false
          }
        }
      }
    }
  }, {
    "call" : "listing",
    "tier" : 2,
    "model" : "test-model",
    "system" : "You extract house listings.",
    "user" : "Two bedroom flat in Indiranagar, rent 25,000.",
    "temperature" : 0,
    "expected" : {
      "model" : "test-model",
      "temperature" : 0,
      "max_tokens" : 2048,
      "messages" : [ {
        "role" : "system",
        "content" : "You extract house listings.\n\nReply with only a JSON object of this shape: {\"type\":\"object\",\"properties\":{\"label\":{\"type\":[\"string\",\"null\"],\"description\":\"Short human label, e.g. '2BHK near Indiranagar metro'\"},\"address\":{\"type\":[\"string\",\"null\"],\"description\":\"Full postal address as written in the listing\"},\"street\":{\"type\":[\"string\",\"null\"],\"description\":\"Street / road name only\"},\"locality\":{\"type\":[\"string\",\"null\"],\"description\":\"Locality / neighbourhood / area\"},\"price\":{\"type\":[\"string\",\"null\"],\"description\":\"Monthly rent or sale price in rupees exactly as written, e.g. '25,000' or '1.2 Cr'\"},\"priceType\":{\"type\":[\"string\",\"null\"],\"description\":\"RENT or SALE\"},\"bedrooms\":{\"type\":[\"string\",\"null\"],\"description\":\"Number of bedrooms, e.g. '2' for 2BHK\"},\"contactName\":{\"type\":[\"string\",\"null\"],\"description\":\"Contact person name\"},\"contactPhone\":{\"type\":[\"string\",\"null\"],\"description\":\"Contact phone number exactly as written\"},\"listingUrl\":{\"type\":[\"string\",\"null\"],\"description\":\"Listing URL if one is present in the text\"},\"notes\":{\"type\":[\"string\",\"null\"],\"description\":\"Other useful facts (deposit, floor, furnishing, availability) in one short paragraph\"},\"amenities\":{\"type\":\"array\",\"description\":\"Amenities such as parking, lift, power backup, gym\",\"items\":{\"type\":\"string\"}}},\"required\":[\"label\",\"address\",\"street\",\"locality\",\"price\",\"priceType\",\"bedrooms\",\"contactName\",\"contactPhone\",\"listingUrl\",\"notes\",\"amenities\"],\"additionalProperties\":false}"
      }, {
        "role" : "user",
        "content" : "Two bedroom flat in Indiranagar, rent 25,000."
      } ],
      "response_format" : {
        "type" : "json_object"
      }
    }
  }, {
    "call" : "listing",
    "tier" : 3,
    "model" : "test-model",
    "system" : "You extract house listings.",
    "user" : "Two bedroom flat in Indiranagar, rent 25,000.",
    "temperature" : 0,
    "expected" : {
      "model" : "test-model",
      "temperature" : 0,
      "max_tokens" : 2048,
      "messages" : [ {
        "role" : "system",
""",
    """        "content" : "You extract house listings.\n\nReply with only a JSON object of this shape: {\"type\":\"object\",\"properties\":{\"label\":{\"type\":[\"string\",\"null\"],\"description\":\"Short human label, e.g. '2BHK near Indiranagar metro'\"},\"address\":{\"type\":[\"string\",\"null\"],\"description\":\"Full postal address as written in the listing\"},\"street\":{\"type\":[\"string\",\"null\"],\"description\":\"Street / road name only\"},\"locality\":{\"type\":[\"string\",\"null\"],\"description\":\"Locality / neighbourhood / area\"},\"price\":{\"type\":[\"string\",\"null\"],\"description\":\"Monthly rent or sale price in rupees exactly as written, e.g. '25,000' or '1.2 Cr'\"},\"priceType\":{\"type\":[\"string\",\"null\"],\"description\":\"RENT or SALE\"},\"bedrooms\":{\"type\":[\"string\",\"null\"],\"description\":\"Number of bedrooms, e.g. '2' for 2BHK\"},\"contactName\":{\"type\":[\"string\",\"null\"],\"description\":\"Contact person name\"},\"contactPhone\":{\"type\":[\"string\",\"null\"],\"description\":\"Contact phone number exactly as written\"},\"listingUrl\":{\"type\":[\"string\",\"null\"],\"description\":\"Listing URL if one is present in the text\"},\"notes\":{\"type\":[\"string\",\"null\"],\"description\":\"Other useful facts (deposit, floor, furnishing, availability) in one short paragraph\"},\"amenities\":{\"type\":\"array\",\"description\":\"Amenities such as parking, lift, power backup, gym\",\"items\":{\"type\":\"string\"}}},\"required\":[\"label\",\"address\",\"street\",\"locality\",\"price\",\"priceType\",\"bedrooms\",\"contactName\",\"contactPhone\",\"listingUrl\",\"notes\",\"amenities\"],\"additionalProperties\":false}"
      }, {
        "role" : "user",
        "content" : "Two bedroom flat in Indiranagar, rent 25,000."
      } ]
    }
  }, {
    "call" : "answer",
    "tier" : 1,
    "model" : "test-model",
    "system" : "You answer questions about saved houses.",
    "user" : "Which house has parking?",
    "temperature" : 0.1,
    "expected" : {
      "model" : "test-model",
      "temperature" : 0.1,
      "max_tokens" : 2048,
      "messages" : [ {
        "role" : "system",
        "content" : "You answer questions about saved houses."
      }, {
        "role" : "user",
        "content" : "Which house has parking?"
      } ],
      "response_format" : {
        "type" : "json_schema",
        "json_schema" : {
          "name" : "answer",
          "strict" : true,
          "schema" : {
            "type" : "object",
            "properties" : {
              "answer" : {
                "type" : "string",
                "description" : "The answer, in 1-6 sentences, citing houses inline as [house:<id>]"
              },
              "citedHouseIds" : {
                "type" : "array",
                "description" : "Ids of the houses cited inline as [house:<id>] in the answer, copied exactly from the context",
                "items" : {
                  "type" : "string"
                }
              }
            },
            "required" : [ "answer", "citedHouseIds" ],
            "additionalProperties" : false
          }
        }
      }
    }
  }, {
    "call" : "answer",
    "tier" : 3,
    "model" : "test-model",
    "system" : "You answer questions about saved houses.",
    "user" : "Which house has parking?",
    "temperature" : 0.1,
    "expected" : {
      "model" : "test-model",
      "temperature" : 0.1,
      "max_tokens" : 2048,
      "messages" : [ {
        "role" : "system",
        "content" : "You answer questions about saved houses.\n\nReply with only a JSON object of this shape: {\"type\":\"object\",\"properties\":{\"answer\":{\"type\":\"string\",\"description\":\"The answer, in 1-6 sentences, citing houses inline as [house:<id>]\"},\"citedHouseIds\":{\"type\":\"array\",\"description\":\"Ids of the houses cited inline as [house:<id>] in the answer, copied exactly from the context\",\"items\":{\"type\":\"string\"}}},\"required\":[\"answer\",\"citedHouseIds\"],\"additionalProperties\":false}"
      }, {
        "role" : "user",
        "content" : "Which house has parking?"
      } ]
    }
  }, {
    "call" : "plan",
    "tier" : 1,
    "model" : "test-model",
    "system" : "You plan house visits.",
    "user" : "Plan a Saturday morning near Koramangala.",
    "temperature" : 0.2,
    "expected" : {
      "model" : "test-model",
      "temperature" : 0.2,
      "max_tokens" : 2048,
      "messages" : [ {
        "role" : "system",
        "content" : "You plan house visits."
      }, {
        "role" : "user",
        "content" : "Plan a Saturday morning near Koramangala."
      } ],
      "response_format" : {
        "type" : "json_schema",
        "json_schema" : {
          "name" : "plan",
          "strict" : true,
          "schema" : {
            "type" : "object",
            "properties" : {
              "summary" : {
                "type" : "string",
                "description" : "2-4 sentences explaining the plan"
              },
              "stops" : {
                "type" : "array",
                "description" : "Houses to visit, in visiting order",
                "items" : {
                  "type" : "object",
                  "properties" : {
                    "houseId" : {
                      "type" : "string",
                      "description" : "House id exactly as returned by a tool"
                    },
                    "reason" : {
                      "type" : "string",
                      "description" : "Why this house is in the plan, one sentence"
                    }
                  },
                  "required" : [ "houseId", "reason" ],
                  "additionalProperties" : false
                }
              }
            },
            "required" : [ "summary", "stops" ],
            "additionalProperties" : false
          }
        }
      }
    }
  }, {
    "call" : "plan",
    "tier" : 2,
    "model" : "test-model",
    "system" : "You plan house visits.",
    "user" : "Plan a Saturday morning near Koramangala.",
    "temperature" : 0.2,
    "expected" : {
      "model" : "test-model",
      "temperature" : 0.2,
      "max_tokens" : 2048,
      "messages" : [ {
        "role" : "system",
        "content" : "You plan house visits.\n\nReply with only a JSON object of this shape: {\"type\":\"object\",\"properties\":{\"summary\":{\"type\":\"string\",\"description\":\"2-4 sentences explaining the plan\"},\"stops\":{\"type\":\"array\",\"description\":\"Houses to visit, in visiting order\",\"items\":{\"type\":\"object\",\"properties\":{\"houseId\":{\"type\":\"string\",\"description\":\"House id exactly as returned by a tool\"},\"reason\":{\"type\":\"string\",\"description\":\"Why this house is in the plan, one sentence\"}},\"required\":[\"houseId\",\"reason\"],\"additionalProperties\":false}}},\"required\":[\"summary\",\"stops\"],\"additionalProperties\":false}"
      }, {
        "role" : "user",
        "content" : "Plan a Saturday morning near Koramangala."
      } ],
      "response_format" : {
        "type" : "json_object"
      }
    }
  }, {
    "call" : "ping",
    "tier" : 3,
    "model" : "test-model",
    "system" : "Reply with {\"ok\": true}.",
    "user" : "ping",
    "temperature" : 0,
    "expected" : {
      "model" : "test-model",
      "temperature" : 0,
      "max_tokens" : 5,
      "messages" : [ {
        "role" : "system",
        "content" : "Reply with {\"ok\": true}."
      }, {
        "role" : "user",
        "content" : "ping"
      } ]
    }
  } ],
  "openaiContent" : [ {
    "response" : "{\"choices\":[{\"message\":{\"role\":\"assistant\",\"content\":\"{\\\"answer\\\":\\\"Yes\\\",\\\"citedHouseIds\\\":[]}\"}}]}",
    "expected" : {
      "text" : "{\"answer\":\"Yes\",\"citedHouseIds\":[]}"
    }
  }, {
    "response" : "{\"choices\":[{\"message\":{\"role\":\"assistant\",\"content\":\"```json\\n{\\\"answer\\\":\\\"Yes\\\",\\\"citedHouseIds\\\":[]}\\n```\"}}]}",
    "expected" : {
      "text" : "{\"answer\":\"Yes\",\"citedHouseIds\":[]}"
    }
  }, {
    "response" : "{\"choices\":[{\"message\":{\"role\":\"assistant\",\"content\":\"```\\n{\\\"ok\\\":true}\\n```\"}}]}",
    "expected" : {
      "text" : "{\"ok\":true}"
    }
  }, {
    "response" : "{\"choices\":[{\"message\":{\"role\":\"assistant\",\"content\":\"  \\n{\\\"ok\\\":true}\\n \"}}]}",
    "expected" : {
      "text" : "{\"ok\":true}"
    }
  }, {
    "response" : "{\"choices\":[{\"message\":{\"role\":\"assistant\",\"content\":\"Sure! {\\\"ok\\\":true}\"}}]}",
    "expected" : {
      "text" : "Sure! {\"ok\":true}"
    }
  }, {
    "response" : "{\"choices\":[]}",
    "expected" : {
      "error" : "unavailable"
    }
  }, {
    "response" : "{\"choices\":[{\"message\":{\"role\":\"assistant\",\"content\":null,\"refusal\":\"I cannot help with that.\"}}]}",
    "expected" : {
      "error" : "unavailable"
    }
  }, {
    "response" : "{\"error\":{\"message\":\"x\"}}",
    "expected" : {
      "error" : "unavailable"
    }
  }, {
    "response" : "not json at all",
    "expected" : {
      "error" : "unavailable"
    }
  } ],
  "providerErrors" : [ {
    "tier" : 1,
    "status" : 0,
    "body" : "",
    "expected" : {
      "action" : "error",
      "kind" : "unreachable"
    }
  }, {
    "tier" : 1,
    "status" : 401,
    "body" : "{\"error\":{\"message\":\"Incorrect API key provided\"}}",
    "expected" : {
      "action" : "error",
      "kind" : "keyRejected"
    }
  }, {
    "tier" : 1,
    "status" : 403,
    "body" : "{\"error\":{\"message\":\"Permission denied\"}}",
    "expected" : {
      "action" : "error",
      "kind" : "keyRejected"
    }
  }, {
    "tier" : 3,
    "status" : 401,
    "body" : "{\"error\":\"unauthorized\"}",
    "expected" : {
      "action" : "error",
      "kind" : "keyRejected"
    }
  }, {
    "tier" : 1,
    "status" : 404,
    "body" : "{\"error\":{\"message\":\"The model `nope` does not exist\",\"code\":\"model_not_found\"}}",
    "expected" : {
      "action" : "error",
      "kind" : "modelNotFound"
    }
  }, {
    "tier" : 2,
    "status" : 404,
    "body" : "{\"error\":\"model 'nope' not found, try pulling it first\"}",
    "expected" : {
      "action" : "error",
      "kind" : "modelNotFound"
    }
  }, {
    "tier" : 1,
    "status" : 429,
    "body" : "{\"error\":{\"message\":\"Rate limit reached\"}}",
    "retryAfter" : "20",
    "expected" : {
      "action" : "error",
      "kind" : "rateLimited",
      "retryAfterSeconds" : 20
    }
  }, {
    "tier" : 1,
    "status" : 429,
    "body" : "{\"error\":{\"message\":\"You exceeded your current quota\"}}",
    "expected" : {
      "action" : "error",
      "kind" : "rateLimited",
      "retryAfterSeconds" : null
    }
  }, {
    "tier" : 1,
    "status" : 400,
    "body" : "{\"error\":{\"message\":\"Invalid parameter: response_format of type json_schema is not supported with this model\"}}",
    "expected" : {
      "action" : "nextTier",
      "tier" : 2
    }
  }, {
    "tier" : 1,
    "status" : 400,
    "body" : "{\"error\":{\"message\":\"'strict' is not permitted\"}}",
    "expected" : {
      "action" : "nextTier",
      "tier" : 2
    }
  }, {
    "tier" : 1,
    "status" : 400,
    "body" : "{\"error\":\"This model does not support structured output: unsupported\"}",
    "expected" : {
      "action" : "nextTier",
      "tier" : 2
    }
  }, {
    "tier" : 1,
    "status" : 400,
    "body" : "{\"error\":{\"message\":\"Invalid request: JSON_SCHEMA not available\"}}",
    "expected" : {
      "action" : "nextTier",
      "tier" : 2
    }
  }, {
    "tier" : 1,
    "status" : 400,
    "body" : "{\"error\":{\"message\":\"max_tokens is too large\"}}",
    "expected" : {
      "action" : "error",
      "kind" : "unavailable"
    }
  }, {
    "tier" : 1,
    "status" : 400,
    "body" : "{\"error\":{\"message\":\"response_format.type must be json_object or text\"}}",
    "expected" : {
      "action" : "nextTier",
      "tier" : 2
    }
  }, {
    "tier" : 2,
    "status" : 400,
    "body" : "{\"error\":{\"message\":\"response_format json_object is not available\"}}",
    "expected" : {
      "action" : "nextTier",
      "tier" : 3
    }
  }, {
    "tier" : 2,
    "status" : 400,
    "body" : "{\"error\":{\"message\":\"Invalid parameter: response_format\"}}",
    "expected" : {
      "action" : "nextTier",
      "tier" : 3
    }
  }, {
    "tier" : 2,
    "status" : 400,
    "body" : "{\"error\":{\"message\":\"unsupported value for strict\"}}",
    "expected" : {
      "action" : "error",
      "kind" : "unavailable"
    }
  }, {
    "tier" : 2,
    "status" : 400,
    "body" : "{\"error\":{\"message\":\"max_tokens is too large\"}}",
    "expected" : {
      "action" : "error",
      "kind" : "unavailable"
    }
  }, {
    "tier" : 3,
    "status" : 400,
    "body" : "{\"error\":{\"message\":\"response_format is not supported\"}}",
    "expected" : {
      "action" : "error",
      "kind" : "unavailable"
    }
  }, {
    "tier" : 1,
    "status" : 500,
    "body" : "{\"error\":{\"message\":\"The server had an error\"}}",
    "expected" : {
      "action" : "error",
      "kind" : "unavailable"
    }
  }, {
    "tier" : 1,
    "status" : 503,
    "body" : "",
    "expected" : {
      "action" : "error",
      "kind" : "unavailable"
    }
  }, {
    "tier" : 1,
    "status" : 502,
    "body" : "",
    "expected" : {
      "action" : "error",
      "kind" : "unavailable"
    }
  }, {
    "provider" : "anthropic",
    "status" : 0,
    "body" : "",
    "expected" : {
      "action" : "error",
      "kind" : "unreachable"
    }
  }, {
    "provider" : "anthropic",
    "status" : 401,
    "body" : "{\"type\":\"error\",\"error\":{\"type\":\"authentication_error\",\"message\":\"invalid x-api-key\"}}",
    "expected" : {
      "action" : "error",
      "kind" : "keyRejected"
    }
  }, {
    "provider" : "anthropic",
    "status" : 403,
    "body" : "{\"type\":\"error\",\"error\":{\"type\":\"permission_error\",\"message\":\"Your API key does not have permission\"}}",
    "expected" : {
      "action" : "error",
      "kind" : "keyRejected"
    }
  }, {
    "provider" : "anthropic",
    "status" : 404,
    "body" : "{\"type\":\"error\",\"error\":{\"type\":\"not_found_error\",\"message\":\"model: test-model\"}}",
    "expected" : {
      "action" : "error",
      "kind" : "modelNotFound"
    }
  }, {
    "provider" : "anthropic",
    "status" : 429,
    "body" : "{\"type\":\"error\",\"error\":{\"type\":\"rate_limit_error\",\"message\":\"Number of requests has exceeded your rate limit\"}}",
    "retryAfter" : "30",
    "expected" : {
      "action" : "error",
      "kind" : "rateLimited",
      "retryAfterSeconds" : 30
    }
  }, {
    "provider" : "anthropic",
    "status" : 429,
    "body" : "{\"type\":\"error\",\"error\":{\"type\":\"rate_limit_error\",\"message\":\"rate limit\"}}",
    "expected" : {
      "action" : "error",
      "kind" : "rateLimited",
      "retryAfterSeconds" : null
""",
    """    }
  }, {
    "provider" : "anthropic",
    "status" : 429,
    "body" : "{}",
    "retryAfter" : "soon",
    "expected" : {
      "action" : "error",
      "kind" : "rateLimited",
      "retryAfterSeconds" : null
    }
  }, {
    "provider" : "anthropic",
    "status" : 400,
    "body" : "{\"type\":\"error\",\"error\":{\"type\":\"invalid_request_error\",\"message\":\"tools.0.input_schema: strict is not supported\"}}",
    "expected" : {
      "action" : "error",
      "kind" : "unavailable"
    }
  }, {
    "provider" : "anthropic",
    "status" : 413,
    "body" : "{\"type\":\"error\",\"error\":{\"type\":\"request_too_large\",\"message\":\"Request exceeds the maximum allowed number of bytes\"}}",
    "expected" : {
      "action" : "error",
      "kind" : "unavailable"
    }
  }, {
    "provider" : "anthropic",
    "status" : 500,
    "body" : "{\"type\":\"error\",\"error\":{\"type\":\"api_error\",\"message\":\"Internal server error\"}}",
    "expected" : {
      "action" : "error",
      "kind" : "unavailable"
    }
  }, {
    "provider" : "anthropic",
    "status" : 529,
    "body" : "{\"type\":\"error\",\"error\":{\"type\":\"overloaded_error\",\"message\":\"Overloaded\"}}",
    "expected" : {
      "action" : "error",
      "kind" : "unavailable"
    }
  }, {
    "provider" : "anthropic",
    "status" : 302,
    "body" : "",
    "expected" : {
      "action" : "error",
      "kind" : "unavailable"
    }
  } ],
  "baseUrl" : [ {
    "input" : "https://api.openai.com/v1",
    "expected" : {
      "valid" : true,
      "normalised" : "https://api.openai.com/v1",
      "host" : "api.openai.com"
    }
  }, {
    "input" : "https://api.openai.com/v1/",
    "expected" : {
      "valid" : true,
      "normalised" : "https://api.openai.com/v1",
      "host" : "api.openai.com"
    }
  }, {
    "input" : "  https://openrouter.ai/api/v1  ",
    "expected" : {
      "valid" : true,
      "normalised" : "https://openrouter.ai/api/v1",
      "host" : "openrouter.ai"
    }
  }, {
    "input" : "HTTPS://API.OpenAI.com/v1/",
    "expected" : {
      "valid" : true,
      "normalised" : "https://api.openai.com/v1",
      "host" : "api.openai.com"
    }
  }, {
    "input" : "https://api.groq.com/openai/v1",
    "expected" : {
      "valid" : true,
      "normalised" : "https://api.groq.com/openai/v1",
      "host" : "api.groq.com"
    }
  }, {
    "input" : "https://example.com",
    "expected" : {
      "valid" : true,
      "normalised" : "https://example.com",
      "host" : "example.com"
    }
  }, {
    "input" : "https://example.com/",
    "expected" : {
      "valid" : true,
      "normalised" : "https://example.com",
      "host" : "example.com"
    }
  }, {
    "input" : "https://example.com:8443/v1",
    "expected" : {
      "valid" : true,
      "normalised" : "https://example.com:8443/v1",
      "host" : "example.com"
    }
  }, {
    "input" : "http://localhost:11434/v1",
    "expected" : {
      "valid" : true,
      "normalised" : "http://localhost:11434/v1",
      "host" : "localhost"
    }
  }, {
    "input" : "http://localhost:1234/v1",
    "expected" : {
      "valid" : true,
      "normalised" : "http://localhost:1234/v1",
      "host" : "localhost"
    }
  }, {
    "input" : "http://localhost",
    "expected" : {
      "valid" : true,
      "normalised" : "http://localhost",
      "host" : "localhost"
    }
  }, {
    "input" : "http://127.0.0.1:11434/v1",
    "expected" : {
      "valid" : true,
      "normalised" : "http://127.0.0.1:11434/v1",
      "host" : "127.0.0.1"
    }
  }, {
    "input" : "http://[::1]:11434/v1",
    "expected" : {
      "valid" : true,
      "normalised" : "http://[::1]:11434/v1",
      "host" : "[::1]"
    }
  }, {
    "input" : "http://10.0.2.2:11434/v1",
    "expected" : {
      "valid" : false,
      "reason" : "insecureHost"
    }
  }, {
    "input" : "http://10.0.2.2:11434/v1",
    "android" : true,
    "expected" : {
      "valid" : true,
      "normalised" : "http://10.0.2.2:11434/v1",
      "host" : "10.0.2.2"
    }
  }, {
    "input" : "https://10.0.2.2/v1",
    "expected" : {
      "valid" : true,
      "normalised" : "https://10.0.2.2/v1",
      "host" : "10.0.2.2"
    }
  }, {
    "input" : "http://192.168.1.20:11434/v1",
    "expected" : {
      "valid" : false,
      "reason" : "insecureHost"
    }
  }, {
    "input" : "http://10.0.0.5/v1",
    "expected" : {
      "valid" : false,
      "reason" : "insecureHost"
    }
  }, {
    "input" : "http://example.com/v1",
    "expected" : {
      "valid" : false,
      "reason" : "insecureHost"
    }
  }, {
    "input" : "http://localhost.evil.com/v1",
    "expected" : {
      "valid" : false,
      "reason" : "insecureHost"
    }
  }, {
    "input" : "http://127.0.0.1.nip.io/v1",
    "expected" : {
      "valid" : false,
      "reason" : "insecureHost"
    }
  }, {
    "input" : "https://user:pass@example.com/v1",
    "expected" : {
      "valid" : false,
      "reason" : "userinfo"
    }
  }, {
    "input" : "https://user@example.com/v1",
    "expected" : {
      "valid" : false,
      "reason" : "userinfo"
    }
  }, {
    "input" : "https://example.com/v1?key=abc",
    "expected" : {
      "valid" : false,
      "reason" : "query"
    }
  }, {
    "input" : "https://example.com/v1#frag",
    "expected" : {
      "valid" : false,
      "reason" : "fragment"
    }
  }, {
    "input" : "https://example.com/v1/chat/completions",
    "expected" : {
      "valid" : false,
      "reason" : "endpoint"
    }
  }, {
    "input" : "https://example.com/v1/chat/completions/",
    "expected" : {
      "valid" : false,
      "reason" : "endpoint"
    }
  }, {
    "input" : "ftp://example.com/v1",
    "expected" : {
      "valid" : false,
      "reason" : "scheme"
    }
  }, {
    "input" : "file:///etc/passwd",
    "expected" : {
      "valid" : false,
      "reason" : "scheme"
    }
  }, {
    "input" : "api.openai.com/v1",
    "expected" : {
      "valid" : false,
      "reason" : "notAnUrl"
    }
  }, {
    "input" : "/v1",
    "expected" : {
      "valid" : false,
      "reason" : "notAnUrl"
    }
  }, {
    "input" : "not a url",
    "expected" : {
      "valid" : false,
      "reason" : "notAnUrl"
    }
  }, {
    "input" : "",
    "expected" : {
      "valid" : false,
      "reason" : "empty"
    }
  }, {
    "input" : "   ",
    "expected" : {
      "valid" : false,
      "reason" : "empty"
    }
  } ],
  "anthropicRequest" : [ {
    "call" : "listing",
    "model" : "test-model",
    "system" : "You extract house listings.",
    "user" : "Two bedroom flat in Indiranagar, rent 25,000.",
    "temperature" : 0,
    "expected" : {
      "model" : "test-model",
      "max_tokens" : 2048,
      "temperature" : 0,
      "system" : "You extract house listings.",
      "messages" : [ {
        "role" : "user",
        "content" : "Two bedroom flat in Indiranagar, rent 25,000."
      } ],
      "tools" : [ {
        "name" : "listing",
        "description" : "Reply by calling this tool with the answer.",
        "input_schema" : {
          "type" : "object",
          "properties" : {
            "label" : {
              "type" : [ "string", "null" ],
              "description" : "Short human label, e.g. '2BHK near Indiranagar metro'"
            },
            "address" : {
              "type" : [ "string", "null" ],
              "description" : "Full postal address as written in the listing"
            },
            "street" : {
              "type" : [ "string", "null" ],
              "description" : "Street / road name only"
            },
            "locality" : {
              "type" : [ "string", "null" ],
              "description" : "Locality / neighbourhood / area"
            },
            "price" : {
              "type" : [ "string", "null" ],
              "description" : "Monthly rent or sale price in rupees exactly as written, e.g. '25,000' or '1.2 Cr'"
            },
            "priceType" : {
              "type" : [ "string", "null" ],
              "description" : "RENT or SALE"
            },
            "bedrooms" : {
              "type" : [ "string", "null" ],
              "description" : "Number of bedrooms, e.g. '2' for 2BHK"
            },
            "contactName" : {
              "type" : [ "string", "null" ],
              "description" : "Contact person name"
            },
            "contactPhone" : {
              "type" : [ "string", "null" ],
              "description" : "Contact phone number exactly as written"
            },
            "listingUrl" : {
              "type" : [ "string", "null" ],
              "description" : "Listing URL if one is present in the text"
            },
            "notes" : {
              "type" : [ "string", "null" ],
              "description" : "Other useful facts (deposit, floor, furnishing, availability) in one short paragraph"
            },
            "amenities" : {
              "type" : "array",
              "description" : "Amenities such as parking, lift, power backup, gym",
              "items" : {
                "type" : "string"
              }
            }
          },
          "required" : [ "label", "address", "street", "locality", "price", "priceType", "bedrooms", "contactName", "contactPhone", "listingUrl", "notes", "amenities" ],
          "additionalProperties" : false
        }
      } ],
      "tool_choice" : {
        "type" : "tool",
        "name" : "listing"
      }
    }
  }, {
    "call" : "answer",
    "model" : "test-model",
    "system" : "You answer questions about saved houses.",
    "user" : "Which house has parking?",
    "temperature" : 0.1,
    "expected" : {
      "model" : "test-model",
      "max_tokens" : 2048,
      "temperature" : 0.1,
      "system" : "You answer questions about saved houses.",
      "messages" : [ {
        "role" : "user",
        "content" : "Which house has parking?"
      } ],
      "tools" : [ {
        "name" : "answer",
        "description" : "Reply by calling this tool with the answer.",
        "input_schema" : {
          "type" : "object",
          "properties" : {
            "answer" : {
              "type" : "string",
              "description" : "The answer, in 1-6 sentences, citing houses inline as [house:<id>]"
            },
            "citedHouseIds" : {
              "type" : "array",
              "description" : "Ids of the houses cited inline as [house:<id>] in the answer, copied exactly from the context",
              "items" : {
                "type" : "string"
              }
            }
          },
          "required" : [ "answer", "citedHouseIds" ],
          "additionalProperties" : false
        }
      } ],
      "tool_choice" : {
        "type" : "tool",
        "name" : "answer"
      }
    }
  }, {
    "call" : "plan",
    "model" : "test-model",
    "system" : "You plan house visits.",
    "user" : "Plan Saturday.",
    "temperature" : 0.2,
    "expected" : {
      "model" : "test-model",
      "max_tokens" : 2048,
      "temperature" : 0.2,
      "system" : "You plan house visits.",
      "messages" : [ {
        "role" : "user",
        "content" : "Plan Saturday."
      } ],
      "tools" : [ {
        "name" : "plan",
        "description" : "Reply by calling this tool with the answer.",
        "input_schema" : {
          "type" : "object",
          "properties" : {
            "summary" : {
              "type" : "string",
              "description" : "2-4 sentences explaining the plan"
            },
            "stops" : {
              "type" : "array",
              "description" : "Houses to visit, in visiting order",
              "items" : {
                "type" : "object",
                "properties" : {
                  "houseId" : {
                    "type" : "string",
                    "description" : "House id exactly as returned by a tool"
                  },
                  "reason" : {
                    "type" : "string",
                    "description" : "Why this house is in the plan, one sentence"
                  }
                },
                "required" : [ "houseId", "reason" ],
                "additionalProperties" : false
              }
            }
          },
          "required" : [ "summary", "stops" ],
          "additionalProperties" : false
        }
      } ],
      "tool_choice" : {
        "type" : "tool",
        "name" : "plan"
      }
    }
  }, {
    "call" : "ping",
    "model" : "test-model",
    "system" : "Reply with {\"ok\": true}.",
    "user" : "ping",
    "temperature" : 0,
    "expected" : {
      "model" : "test-model",
      "max_tokens" : 5,
      "temperature" : 0,
      "system" : "Reply with {\"ok\": true}.",
      "messages" : [ {
        "role" : "user",
        "content" : "ping"
      } ]
    }
  } ],
  "anthropicContent" : [ {
    "call" : "generate",
    "response" : "{\"id\":\"msg_test\",\"type\":\"message\",\"role\":\"assistant\",\"model\":\"test-model\",\"content\":[{\"type\":\"tool_use\",\"id\":\"toolu_test\",\"name\":\"answer\",\"input\":{\"answer\":\"Yes\",\"citedHouseIds\":[]}}],\"stop_reason\":\"tool_use\"}",
    "expected" : {
      "text" : "{\"answer\":\"Yes\",\"citedHouseIds\":[]}"
    }
  }, {
    "call" : "generate",
    "response" : "{\"id\":\"msg_test\",\"type\":\"message\",\"role\":\"assistant\",\"model\":\"test-model\",\"content\":[{\"type\":\"text\",\"text\":\"Checking the notes.\"},{\"type\":\"tool_use\",\"id\":\"toolu_test\",\"name\":\"answer\",\"input\":{\"answer\":\"Yes\",\"citedHouseIds\":[]}}],\"stop_reason\":\"tool_use\"}",
    "expected" : {
      "text" : "{\"answer\":\"Yes\",\"citedHouseIds\":[]}"
    }
  }, {
    "call" : "generate",
    "response" : "{\"id\":\"msg_test\",\"type\":\"message\",\"role\":\"assistant\",\"model\":\"test-model\",\"content\":[{\"type\":\"tool_use\",\"id\":\"toolu_test\",\"name\":\"answer\",\"input\":{\"answer\":\"Yes\",\"citedHouseIds\":[]}},{\"type\":\"tool_use\",\"id\":\"toolu_test\",\"name\":\"answer\",\"input\":{\"answer\":\"No\",\"citedHouseIds\":[]}}],\"stop_reason\":\"tool_use\"}",
    "expected" : {
      "text" : "{\"answer\":\"Yes\",\"citedHouseIds\":[]}"
    }
  }, {
    "call" : "generate",
    "response" : "{\"id\":\"msg_test\",\"type\":\"message\",\"role\":\"assistant\",\"model\":\"test-model\",\"content\":[{\"type\":\"tool_use\",\"id\":\"toolu_test\",\"name\":\"listing\",\"input\":{\"label\":\"2BHK\",\"price\":null,\"rooms\":[\"hall\",\"kitchen\"]}}],\"stop_reason\":\"tool_use\"}",
    "expected" : {
      "text" : "{\"label\":\"2BHK\",\"price\":null,\"rooms\":[\"hall\",\"kitchen\"]}"
    }
  }, {
    "call" : "generate",
    "response" : "{\"id\":\"msg_test\",\"type\":\"message\",\"role\":\"assistant\",\"model\":\"test-model\",\"content\":[{\"type\":\"tool_use\",\"id\":\"toolu_test\",\"name\":\"answer\",\"input\":{\"answer\":\"Yes\",\"citedHouseIds\":[]}}],\"stop_reason\":\"end_turn\"}",
    "expected" : {
      "text" : "{\"answer\":\"Yes\",\"citedHouseIds\":[]}"
""",
    """    }
  }, {
    "call" : "generate",
    "response" : "{\"id\":\"msg_test\",\"type\":\"message\",\"role\":\"assistant\",\"model\":\"test-model\",\"content\":[{\"type\":\"tool_use\",\"id\":\"toolu_test\",\"name\":\"answer\",\"input\":{\"answer\":\"Yes, bal\"}}],\"stop_reason\":\"max_tokens\"}",
    "expected" : {
      "error" : "unavailable"
    }
  }, {
    "call" : "generate",
    "response" : "{\"id\":\"msg_test\",\"type\":\"message\",\"role\":\"assistant\",\"model\":\"test-model\",\"content\":[{\"type\":\"text\",\"text\":\"I cannot help with that.\"}],\"stop_reason\":\"refusal\"}",
    "expected" : {
      "error" : "unavailable"
    }
  }, {
    "call" : "generate",
    "response" : "{\"id\":\"msg_test\",\"type\":\"message\",\"role\":\"assistant\",\"model\":\"test-model\",\"content\":[{\"type\":\"text\",\"text\":\"{\\\"answer\\\":\\\"Yes\\\",\\\"citedHouseIds\\\":[]}\"}],\"stop_reason\":\"end_turn\"}",
    "expected" : {
      "error" : "unavailable"
    }
  }, {
    "call" : "generate",
    "response" : "{\"id\":\"msg_test\",\"type\":\"message\",\"role\":\"assistant\",\"model\":\"test-model\",\"content\":[],\"stop_reason\":\"end_turn\"}",
    "expected" : {
      "error" : "unavailable"
    }
  }, {
    "call" : "generate",
    "response" : "{\"id\":\"msg_test\",\"type\":\"message\",\"role\":\"assistant\",\"model\":\"test-model\",\"content\":[{\"type\":\"tool_use\",\"id\":\"toolu_test\",\"name\":\"answer\",\"input\":\"not an object\"}],\"stop_reason\":\"tool_use\"}",
    "expected" : {
      "error" : "unavailable"
    }
  }, {
    "call" : "generate",
    "response" : "{\"type\":\"message\",\"role\":\"assistant\"}",
    "expected" : {
      "error" : "unavailable"
    }
  }, {
    "call" : "generate",
    "response" : "not json",
    "expected" : {
      "error" : "unavailable"
    }
  }, {
    "call" : "ping",
    "response" : "{\"id\":\"msg_test\",\"type\":\"message\",\"role\":\"assistant\",\"model\":\"test-model\",\"content\":[{\"type\":\"text\",\"text\":\"{\\\"ok\\\"\"}],\"stop_reason\":\"max_tokens\"}",
    "expected" : {
      "ok" : true
    }
  }, {
    "call" : "ping",
    "response" : "{\"id\":\"msg_test\",\"type\":\"message\",\"role\":\"assistant\",\"model\":\"test-model\",\"content\":[],\"stop_reason\":\"end_turn\"}",
    "expected" : {
      "ok" : true
    }
  }, {
    "call" : "ping",
    "response" : "{\"type\":\"message\"}",
    "expected" : {
      "error" : "unavailable"
    }
  }, {
    "call" : "ping",
    "response" : "not json",
    "expected" : {
      "error" : "unavailable"
    }
  } ],
  "routes" : [ {
    "name" : "Mumbai, one afternoon: Bandra station, Bandra West, Powai, Andheri East",
    "start" : [ 19.0544, 72.8402 ],
    "points" : [ [ "bandra", 19.0596, 72.8295 ], [ "powai", 19.1176, 72.906 ], [ "andheri", 19.1136, 72.8697 ] ],
    "nearestNeighbour" : [ {
      "id" : "bandra",
      "meters" : 1265,
      "walkMinutes" : 21
    }, {
      "id" : "andheri",
      "meters" : 7342,
      "walkMinutes" : 120
    }, {
      "id" : "powai",
      "meters" : 3840,
      "walkMinutes" : 63
    } ],
    "inOrder" : [ {
      "id" : "bandra",
      "meters" : 1265,
      "walkMinutes" : 21
    }, {
      "id" : "powai",
      "meters" : 10306,
      "walkMinutes" : 168
    }, {
      "id" : "andheri",
      "meters" : 3840,
      "walkMinutes" : 63
    } ]
  }, {
    "name" : "Chennai to Guwahati: 2,600 km is one leg, and the estimate does not pretend to be a walk",
    "start" : [ 13.0827, 80.2707 ],
    "points" : [ [ "adyar", 13.0012, 80.2565 ], [ "beltola", 26.125, 91.8 ], [ "velachery", 13.0067, 80.2206 ] ],
    "nearestNeighbour" : [ {
      "id" : "adyar",
      "meters" : 9192,
      "walkMinutes" : 150
    }, {
      "id" : "velachery",
      "meters" : 3937,
      "walkMinutes" : 64
    }, {
      "id" : "beltola",
      "meters" : 1894792,
      "walkMinutes" : 30791
    } ],
    "inOrder" : [ {
      "id" : "adyar",
      "meters" : 9192,
      "walkMinutes" : 150
    }, {
      "id" : "beltola",
      "meters" : 1892885,
      "walkMinutes" : 30760
    }, {
      "id" : "velachery",
      "meters" : 1894792,
      "walkMinutes" : 30791
    } ]
  }, {
    "name" : "India extremes from Kanyakumari: Lakshadweep, Port Blair, Srinagar, Kutch, Arunachal, Indira Point",
    "start" : [ 8.0883, 77.5385 ],
    "points" : [ [ "kavaratti", 10.5626, 72.6369 ], [ "port-blair", 11.6234, 92.7265 ], [ "srinagar", 34.0837, 74.7973 ], [ "guhar-moti", 23.72, 68.12 ], [ "kibithu", 28.2, 97.0 ], [ "indira-point", 6.7456, 93.8403 ] ],
    "nearestNeighbour" : [ {
      "id" : "kavaratti",
      "meters" : 604074,
      "walkMinutes" : 9817
    }, {
      "id" : "guhar-moti",
      "meters" : 1539323,
      "walkMinutes" : 25015
    }, {
      "id" : "srinagar",
      "meters" : 1322193,
      "walkMinutes" : 21486
    }, {
      "id" : "kibithu",
      "meters" : 2206731,
      "walkMinutes" : 35860
    }, {
      "id" : "port-blair",
      "meters" : 1896096,
      "walkMinutes" : 30812
    }, {
      "id" : "indira-point",
      "meters" : 555988,
      "walkMinutes" : 9035
    } ],
    "inOrder" : [ {
      "id" : "kavaratti",
      "meters" : 604074,
      "walkMinutes" : 9817
    }, {
      "id" : "port-blair",
      "meters" : 2194844,
      "walkMinutes" : 35667
    }, {
      "id" : "srinagar",
      "meters" : 3088928,
      "walkMinutes" : 50196
    }, {
      "id" : "guhar-moti",
      "meters" : 1322193,
      "walkMinutes" : 21486
    }, {
      "id" : "kibithu",
      "meters" : 2922813,
      "walkMinutes" : 47496
    }, {
      "id" : "indira-point",
      "meters" : 2408693,
      "walkMinutes" : 39142
    } ]
  }, {
    "name" : "Hills: Dehradun, Mussoorie, Rishikesh, Haridwar",
    "start" : [ 30.3243, 78.0415 ],
    "points" : [ [ "mussoorie", 30.4598, 78.0664 ], [ "rishikesh", 30.0869, 78.2676 ], [ "haridwar", 29.9457, 78.1642 ] ],
    "nearestNeighbour" : [ {
      "id" : "mussoorie",
      "meters" : 15255,
      "walkMinutes" : 248
    }, {
      "id" : "rishikesh",
      "meters" : 45745,
      "walkMinutes" : 744
    }, {
      "id" : "haridwar",
      "meters" : 18591,
      "walkMinutes" : 303
    } ],
    "inOrder" : [ {
      "id" : "mussoorie",
      "meters" : 15255,
      "walkMinutes" : 248
    }, {
      "id" : "rishikesh",
      "meters" : 45745,
      "walkMinutes" : 744
    }, {
      "id" : "haridwar",
      "meters" : 18591,
      "walkMinutes" : 303
    } ]
  }, {
    "name" : "Two flats in one tower (same coordinates): the first in the list is first",
    "start" : [ 31.1048, 77.1734 ],
    "points" : [ [ "sanjauli-a", 31.101, 77.202 ], [ "sanjauli-b", 31.101, 77.202 ], [ "chotta-shimla", 31.094, 77.185 ] ],
    "nearestNeighbour" : [ {
      "id" : "chotta-shimla",
      "meters" : 1632,
      "walkMinutes" : 27
    }, {
      "id" : "sanjauli-a",
      "meters" : 1796,
      "walkMinutes" : 30
    }, {
      "id" : "sanjauli-b",
      "meters" : 0,
      "walkMinutes" : 0
    } ],
    "inOrder" : [ {
      "id" : "sanjauli-a",
      "meters" : 2756,
      "walkMinutes" : 45
    }, {
      "id" : "sanjauli-b",
      "meters" : 0,
      "walkMinutes" : 0
    }, {
      "id" : "chotta-shimla",
      "meters" : 1796,
      "walkMinutes" : 30
    } ]
  }, {
    "name" : "One house",
    "start" : [ 22.5867, 88.4171 ],
    "points" : [ [ "ballygunge", 22.529, 88.365 ] ],
    "nearestNeighbour" : [ {
      "id" : "ballygunge",
      "meters" : 8354,
      "walkMinutes" : 136
    } ],
    "inOrder" : [ {
      "id" : "ballygunge",
      "meters" : 8354,
      "walkMinutes" : 136
    } ]
  }, {
    "name" : "No houses",
    "start" : [ 12.9716, 77.5946 ],
    "points" : [ ],
    "nearestNeighbour" : [ ],
    "inOrder" : [ ]
  }, {
    "name" : "Start on the house: 0 m, 0 minutes",
    "start" : [ 26.85, 81.0 ],
    "points" : [ [ "gomti-nagar", 26.85, 81.0 ] ],
    "nearestNeighbour" : [ {
      "id" : "gomti-nagar",
      "meters" : 0,
      "walkMinutes" : 0
    } ],
    "inOrder" : [ {
      "id" : "gomti-nagar",
      "meters" : 0,
      "walkMinutes" : 0
    } ]
  } ],
  "rupees" : [ {
    "amount" : 0,
    "expected" : "₹0"
  }, {
    "amount" : 999,
    "expected" : "₹999"
  }, {
    "amount" : 1000,
    "expected" : "₹1,000"
  }, {
    "amount" : 9500,
    "expected" : "₹9,500"
  }, {
    "amount" : 22000,
    "expected" : "₹22,000"
  }, {
    "amount" : 28000,
    "expected" : "₹28,000"
  }, {
    "amount" : 85000,
    "expected" : "₹85,000"
  }, {
    "amount" : 99999,
    "expected" : "₹99,999"
  }, {
    "amount" : 100000,
    "expected" : "₹1,00,000"
  }, {
    "amount" : 120000,
    "expected" : "₹1,20,000"
  }, {
    "amount" : 1234567,
    "expected" : "₹12,34,567"
  }, {
    "amount" : 8500000,
    "expected" : "₹85,00,000"
  }, {
    "amount" : 12500000,
    "expected" : "₹1,25,00,000"
  }, {
    "amount" : 28000000,
    "expected" : "₹2,80,00,000"
  }, {
    "amount" : 45000000,
    "expected" : "₹4,50,00,000"
  }, {
    "amount" : 100000000,
    "expected" : "₹10,00,00,000"
  }, {
    "amount" : 1234567890,
    "expected" : "₹1,23,45,67,890"
  } ]
}""",
).joinToString("")
