import org.jetbrains.kotlin.gradle.dsl.JvmTarget

// :shared - Kotlin Multiplatform module with Doorprints' platform-neutral code (see README.md in this folder).
// Targets: Android (AGP's KMP library plugin) and, compile-only, iosArm64 + iosSimulatorArm64. The iOS targets exist
// so commonMain cannot use JVM/Android APIs; there is no iOS app and no iOS framework binary in this sprint.
plugins {
    alias(libs.plugins.kotlin.multiplatform)
    alias(libs.plugins.android.kotlin.multiplatform.library)
    alias(libs.plugins.kotlin.serialization)
    // Room KMP (CMP-4 P4a, ADR-23): the database in commonMain, its code generated by KSP for each target.
    alias(libs.plugins.ksp)
    alias(libs.plugins.androidx.room)
}

kotlin {
    // AGP 9 name for the Android target of a KMP library (androidLibrary {} is deprecated since AGP 9.1).
    android {
        namespace = "app.doorprints.shared"
        compileSdk = 37
        minSdk = 26
        compilerOptions.jvmTarget = JvmTarget.JVM_17
        // Host (JVM) tests are off by default in this plugin; they run commonTest + androidHostTest as the Gradle
        // task :shared:testAndroidHostTest (the app's testDebugUnitTest depends on it, see app/build.gradle.kts).
        withHostTest {}
    }

    // Compile-only guard rails for Phase 2. Built by the macOS CI job (shared-ios.yml: compileKotlinIosArm64,
    // compileKotlinIosSimulatorArm64, compileTestKotlinIosSimulatorArm64). On ubuntu these tasks are skipped, also
    // under :shared:allTests, because gradle.properties sets kotlin.native.enableKlibsCrossCompilation=false.
    iosArm64()
    iosSimulatorArm64()

    sourceSets {
        commonMain.dependencies {
            // api: ApiClient takes an HttpClient, so :app sees Ktor's client types.
            api(libs.ktor.client.core)
            implementation(libs.kotlinx.coroutines.core)
            implementation(libs.kotlinx.serialization.json)
            // api: AppDatabase is a RoomDatabase, and :app builds it and calls its DAOs (data/AppDatabaseFactory.kt).
            api(libs.androidx.room.runtime)
            // api: SettingsStore takes a DataStore<Preferences>, which :app opens on the settings file (CMP-4 P4b).
            api(libs.androidx.datastore.preferences.core)
        }
        iosMain.dependencies {
            // iOS has no framework SQLite for Room: the bundled driver (compile-only until the iOS shell, CMP-8).
            implementation(libs.androidx.sqlite.bundled)
        }
        commonTest.dependencies {
            implementation(libs.kotlin.test)
            implementation(libs.kotlinx.coroutines.test)
            implementation(libs.ktor.client.mock)
        }
        androidMain.dependencies {
            implementation(libs.ktor.client.okhttp)
        }
        getByName("androidHostTest").dependencies {
            implementation(libs.kotlin.test.junit)
        }
    }
}

// Room KMP (CMP-4 P4a). The schema JSON is committed in shared/schemas/app.doorprints.data.AppDatabase/ (moved from
// app/schemas; the folder is named after the class, whose package app.doorprints.data did not change) and pinned by
// RoomSchemaTest. Android opens the same file (doorprints.db) with the framework SQLite as before; see :app's
// data/AppDatabaseFactory.kt.
room {
    schemaDirectory("$projectDir/schemas")
}

dependencies {
    add("kspAndroid", libs.androidx.room.compiler)
    add("kspIosArm64", libs.androidx.room.compiler)
    add("kspIosSimulatorArm64", libs.androidx.room.compiler)
}
