#!/usr/bin/env python3
# Copyright 2026 Sriram (Sriram-Codes-SW)
#
# This file is part of Doorprints.
#
# Doorprints is free software: you can redistribute it and/or modify it under the terms of the GNU Affero General
# Public License as published by the Free Software Foundation, version 3 of the License.
#
# Doorprints is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied
# warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Affero General Public License for more
# details.
#
# You should have received a copy of the GNU Affero General Public License along with Doorprints (the file LICENSE;
# the file NOTICE has additional permissions under section 7). If not, see <https://www.gnu.org/licenses/>.
#
# SPDX-License-Identifier: AGPL-3.0-only
"""Copies docs/ai/evals/parity-vectors.json into :shared's common tests (ParityVectorsJson.kt), so the parity checks
also run on iOS, where a test cannot read a file from the repository, and into the website's tests
(web/src/app/core/ai/parity-vectors.json), whose build reads files under web/ only. Run after changing the vectors; the
JVM test ParityVectorsFileTest fails while either copy differs from the file."""
import pathlib

ROOT = pathlib.Path(__file__).resolve().parents[2]
SRC = ROOT / "docs/ai/evals/parity-vectors.json"
OUT = ROOT / "android/shared/src/commonTest/kotlin/app/doorprints/shared/ai/ParityVectorsJson.kt"
HEADER = (ROOT / "android/shared/src/commonMain/kotlin/app/doorprints/shared/ai/PromptSafety.kt").read_text().split("package")[0]

text = SRC.read_text(encoding="utf-8")
escaped = text.replace("$", "${'$'}")
assert '"""' not in escaped
OUT.write_text(
    HEADER
    + "package app.doorprints.shared.ai\n\n"
    + "// Generated by .github/scripts/parity-vectors-kotlin.py from docs/ai/evals/parity-vectors.json; do not edit.\n\n"
    + "/** The shared AI test vectors, as text, for the common tests (see [ParityVectorsTest]). */\n"
    + 'internal const val PARITY_VECTORS_JSON: String = """' + escaped + '"""\n',
    encoding="utf-8",
)
WEB = ROOT / "web/src/app/core/ai/parity-vectors.json"
WEB.write_text(text, encoding="utf-8")
print("wrote", OUT.relative_to(ROOT), "and", WEB.relative_to(ROOT))
