package app.doorprints.shared.export

/**
 * The words that appear **inside** an exported copy, in the export language (docs/11 section 5.2: "language
 * (en/hi/ta/te)" is an export option, separate from the app's own language).
 *
 * They live here, not in the apps' own string catalogues (`res/values-hi/strings.xml` and the web's i18n
 * files), for three reasons:
 *  * the export language is chosen per export, so a copy in Tamil must be possible while the phone runs in English;
 *  * `commonMain` has no access to Android resources, and the same table has to drive the web exporters;
 *  * golden tests can only pin the output if the headings are part of the pinned code.
 *
 * The house-status and checklist wordings are copied from the app's `strings.xml` (and the web's catalogues) on
 * purpose, so an exported table reads like the screen it came from. Values that are shown to the user in the app
 * UI stay in `strings.xml`; only export-document text belongs here.
 *
 * Every language must define the same keys; `ExportStringsTest` fails if one is missing or spare.
 */
class ExportStrings internal constructor(
    val language: String,
    private val values: Map<String, String>,
) {
    /** @throws IllegalStateException for an unknown key, which is a programming error, not user input. */
    operator fun get(key: String): String = values[key] ?: error("No export string '$key' for '$language'")

    /** Translated label of a checklist key ([app.doorprints.shared.model.Checklist.keys]); the key itself if new. */
    fun check(key: String): String = values["check.$key"] ?: key

    fun status(name: String): String = values["status.$name"] ?: name

    fun source(name: String): String = values["source.$name"] ?: name

    fun priceType(name: String?): String = values["priceType.${name ?: "RENT"}"] ?: (name ?: "")

    internal val keys: Set<String> get() = values.keys

    companion object {
        /** Falls back to English for anything outside en/hi/ta/te (the app never offers another language). */
        fun of(language: String): ExportStrings = when (language) {
            "hi" -> HI
            "ta" -> TA
            "te" -> TE
            else -> EN
        }

        val EN = ExportStrings(
            "en",
            mapOf(
                "doc.title" to "Doorprints — my houses",
                "doc.subtitle" to "A copy of everything saved on my phone",
                "cover.exported" to "Copy made",
                "cover.times" to "Times shown for UTC",
                "cover.counts" to "What is in this copy",
                "cover.houses" to "Houses",
                "cover.visits" to "Visits",
                "cover.photos" to "Photos",
                "cover.options" to "Options",
                "cover.scope" to "Houses included",
                "cover.rejected" to "Rejected houses included",
                "cover.photoScope" to "Photos included",
                "cover.contacts" to "Contact details",
                "cover.language" to "Language",
                "cover.privacy" to "This copy is not encrypted. Anyone who opens the file can read everything in it. Keep it somewhere safe.",
                "cover.contactWarning" to "This copy contains phone numbers of owners and brokers. Share it carefully.",
                "scope.ALL" to "All",
                "scope.SHORTLISTED" to "Shortlisted only",
                "scope.SELECTED" to "Selected houses",
                "photoScope.ALL" to "All",
                "photoScope.SHORTLISTED" to "Shortlisted only",
                "photoScope.NONE" to "None",
                "yes" to "Yes",
                "no" to "No",
                "none" to "—",
                "section.ranking" to "Best first",
                "section.details" to "Details",
                "section.checklist" to "What I checked",
                "section.visits" to "Visits",
                "section.notes" to "Notes",
                "section.photos" to "Photos",
                "section.contact" to "Contact",
                "photos.inBackup" to "The photo files are in the photos folder of this backup.",
                "table.houses" to "Houses",
                "table.scores" to "Scores",
                "table.visits" to "Visits",
                "table.photos" to "Photos",
                "col.rank" to "Rank",
                "col.id" to "Id",
                "col.houseId" to "House id",
                "col.house" to "House",
                "col.label" to "House",
                "col.status" to "Status",
                "col.score" to "Score",
                "col.price" to "Price",
                "col.priceType" to "Price type",
                "col.bedrooms" to "Bedrooms",
                "col.rating" to "Stars",
                "col.address" to "Address",
                "col.street" to "Street",
                "col.locality" to "Locality",
                "col.lat" to "Latitude",
                "col.lon" to "Longitude",
                "col.contactName" to "Contact name",
                "col.contactPhone" to "Phone",
                "col.listingUrl" to "Listing link",
                "col.notes" to "Notes",
                "col.visits" to "Visits",
                "col.photos" to "Photos",
                "col.createdAt" to "Added",
                "col.updatedAt" to "Last changed",
                "col.item" to "Item key",
                "col.itemLabel" to "What",
                "col.arrivedAt" to "Arrived",
                "col.leftAt" to "Left",
                "col.minutes" to "Minutes",
                "col.source" to "How recorded",
                "col.fileName" to "File",
                "status.NEW" to "New",
                "status.SHORTLISTED" to "Shortlisted",
                "status.REJECTED" to "Rejected",
                "priceType.RENT" to "Rent per month",
                "priceType.SALE" to "Sale price",
                "source.AUTO" to "Automatic",
                "source.MANUAL" to "Added by me",
                "check.water" to "Water supply",
                "check.power" to "Power backup",
                "check.parking" to "Parking",
                "check.sunlight" to "Sunlight",
                "check.ventilation" to "Ventilation",
                "check.noise" to "Quiet (low noise)",
                "check.security" to "Safety and security",
                "check.maintenance" to "Building condition",
                "check.neighbourhood" to "Neighbourhood",
                "check.commute" to "Commute",
            ),
        )

        val HI = ExportStrings(
            "hi",
            mapOf(
                "doc.title" to "Doorprints — मेरे मकान",
                "doc.subtitle" to "मेरे फ़ोन में सहेजी हर चीज़ की एक प्रति",
                "cover.exported" to "प्रति बनाई गई",
                "cover.times" to "समय UTC के अनुसार",
                "cover.counts" to "इस प्रति में क्या है",
                "cover.houses" to "मकान",
                "cover.visits" to "दौरे",
                "cover.photos" to "तस्वीरें",
                "cover.options" to "विकल्प",
                "cover.scope" to "शामिल मकान",
                "cover.rejected" to "अस्वीकृत मकान शामिल",
                "cover.photoScope" to "शामिल तस्वीरें",
                "cover.contacts" to "संपर्क विवरण",
                "cover.language" to "भाषा",
                "cover.privacy" to "यह प्रति एन्क्रिप्ट नहीं है। जो भी इस फ़ाइल को खोलेगा वह सब कुछ पढ़ सकता है। इसे सुरक्षित जगह रखें।",
                "cover.contactWarning" to "इस प्रति में मालिकों और दलालों के फ़ोन नंबर हैं। इसे सोच-समझकर साझा करें।",
                "scope.ALL" to "सभी",
                "scope.SHORTLISTED" to "केवल चुने गए",
                "scope.SELECTED" to "चयनित मकान",
                "photoScope.ALL" to "सभी",
                "photoScope.SHORTLISTED" to "केवल चुने गए",
                "photoScope.NONE" to "कोई नहीं",
                "yes" to "हाँ",
                "no" to "नहीं",
                "none" to "—",
                "section.ranking" to "सबसे अच्छे पहले",
                "section.details" to "विवरण",
                "section.checklist" to "मैंने क्या जाँचा",
                "section.visits" to "दौरे",
                "section.notes" to "नोट",
                "section.photos" to "तस्वीरें",
                "section.contact" to "संपर्क",
                "photos.inBackup" to "तस्वीरों की फ़ाइलें इस बैकअप के photos फ़ोल्डर में हैं।",
                "table.houses" to "मकान",
                "table.scores" to "अंक",
                "table.visits" to "दौरे",
                "table.photos" to "तस्वीरें",
                "col.rank" to "क्रम",
                "col.id" to "आईडी",
                "col.houseId" to "मकान आईडी",
                "col.house" to "मकान",
                "col.label" to "मकान",
                "col.status" to "स्थिति",
                "col.score" to "अंक",
                "col.price" to "कीमत",
                "col.priceType" to "कीमत का प्रकार",
                "col.bedrooms" to "बेडरूम",
                "col.rating" to "सितारे",
                "col.address" to "पता",
                "col.street" to "सड़क",
                "col.locality" to "इलाका",
                "col.lat" to "अक्षांश",
                "col.lon" to "देशांतर",
                "col.contactName" to "संपर्क नाम",
                "col.contactPhone" to "फ़ोन",
                "col.listingUrl" to "लिस्टिंग लिंक",
                "col.notes" to "नोट",
                "col.visits" to "दौरे",
                "col.photos" to "तस्वीरें",
                "col.createdAt" to "जोड़ा गया",
                "col.updatedAt" to "आख़िरी बदलाव",
                "col.item" to "आइटम की",
                "col.itemLabel" to "क्या",
                "col.arrivedAt" to "पहुँचे",
                "col.leftAt" to "निकले",
                "col.minutes" to "मिनट",
                "col.source" to "कैसे दर्ज हुआ",
                "col.fileName" to "फ़ाइल",
                "status.NEW" to "नया",
                "status.SHORTLISTED" to "चुना गया",
                "status.REJECTED" to "अस्वीकृत",
                "priceType.RENT" to "किराया प्रति माह",
                "priceType.SALE" to "बिक्री कीमत",
                "source.AUTO" to "अपने आप",
                "source.MANUAL" to "मैंने जोड़ा",
                "check.water" to "पानी की आपूर्ति",
                "check.power" to "बिजली बैकअप",
                "check.parking" to "पार्किंग",
                "check.sunlight" to "धूप",
                "check.ventilation" to "हवादारी",
                "check.noise" to "शांति (कम शोर)",
                "check.security" to "सुरक्षा",
                "check.maintenance" to "इमारत की हालत",
                "check.neighbourhood" to "आस-पड़ोस",
                "check.commute" to "आने-जाने की सुविधा",
            ),
        )

        val TA = ExportStrings(
            "ta",
            mapOf(
                "doc.title" to "Doorprints — என் வீடுகள்",
                "doc.subtitle" to "என் தொலைபேசியில் சேமித்த அனைத்தின் நகல்",
                "cover.exported" to "நகல் எடுக்கப்பட்டது",
                "cover.times" to "நேரங்கள் UTC அடிப்படையில்",
                "cover.counts" to "இந்த நகலில் உள்ளவை",
                "cover.houses" to "வீடுகள்",
                "cover.visits" to "வருகைகள்",
                "cover.photos" to "படங்கள்",
                "cover.options" to "விருப்பங்கள்",
                "cover.scope" to "சேர்க்கப்பட்ட வீடுகள்",
                "cover.rejected" to "நிராகரிக்கப்பட்ட வீடுகளும் உள்ளன",
                "cover.photoScope" to "சேர்க்கப்பட்ட படங்கள்",
                "cover.contacts" to "தொடர்பு விவரங்கள்",
                "cover.language" to "மொழி",
                "cover.privacy" to "இந்த நகல் மறையாக்கம் செய்யப்படவில்லை. இந்தக் கோப்பைத் திறக்கும் எவரும் எல்லாவற்றையும் படிக்க முடியும். பாதுகாப்பான இடத்தில் வைக்கவும்.",
                "cover.contactWarning" to "இந்த நகலில் உரிமையாளர்கள் மற்றும் தரகர்களின் தொலைபேசி எண்கள் உள்ளன. கவனமாகப் பகிரவும்.",
                "scope.ALL" to "அனைத்தும்",
                "scope.SHORTLISTED" to "தேர்வானவை மட்டும்",
                "scope.SELECTED" to "தேர்ந்தெடுத்த வீடுகள்",
                "photoScope.ALL" to "அனைத்தும்",
                "photoScope.SHORTLISTED" to "தேர்வானவை மட்டும்",
                "photoScope.NONE" to "எதுவும் இல்லை",
                "yes" to "ஆம்",
                "no" to "இல்லை",
                "none" to "—",
                "section.ranking" to "சிறந்தவை முதலில்",
                "section.details" to "விவரங்கள்",
                "section.checklist" to "நான் சரிபார்த்தவை",
                "section.visits" to "வருகைகள்",
                "section.notes" to "குறிப்புகள்",
                "section.photos" to "படங்கள்",
                "section.contact" to "தொடர்பு",
                "photos.inBackup" to "படக் கோப்புகள் இந்த காப்புப்பிரதியின் photos கோப்புறையில் உள்ளன.",
                "table.houses" to "வீடுகள்",
                "table.scores" to "மதிப்பெண்கள்",
                "table.visits" to "வருகைகள்",
                "table.photos" to "படங்கள்",
                "col.rank" to "வரிசை",
                "col.id" to "அடையாளம்",
                "col.houseId" to "வீட்டு அடையாளம்",
                "col.house" to "வீடு",
                "col.label" to "வீடு",
                "col.status" to "நிலை",
                "col.score" to "மதிப்பெண்",
                "col.price" to "விலை",
                "col.priceType" to "விலை வகை",
                "col.bedrooms" to "படுக்கையறைகள்",
                "col.rating" to "நட்சத்திரங்கள்",
                "col.address" to "முகவரி",
                "col.street" to "தெரு",
                "col.locality" to "பகுதி",
                "col.lat" to "அட்சரேகை",
                "col.lon" to "தீர்க்கரேகை",
                "col.contactName" to "தொடர்பு பெயர்",
                "col.contactPhone" to "தொலைபேசி",
                "col.listingUrl" to "விளம்பர இணைப்பு",
                "col.notes" to "குறிப்புகள்",
                "col.visits" to "வருகைகள்",
                "col.photos" to "படங்கள்",
                "col.createdAt" to "சேர்க்கப்பட்டது",
                "col.updatedAt" to "கடைசி மாற்றம்",
                "col.item" to "உருப்படிக் குறியீடு",
                "col.itemLabel" to "என்ன",
                "col.arrivedAt" to "வந்த நேரம்",
                "col.leftAt" to "சென்ற நேரம்",
                "col.minutes" to "நிமிடங்கள்",
                "col.source" to "எப்படிப் பதிவானது",
                "col.fileName" to "கோப்பு",
                "status.NEW" to "புதியது",
                "status.SHORTLISTED" to "தேர்வானது",
                "status.REJECTED" to "நிராகரிக்கப்பட்டது",
                "priceType.RENT" to "மாத வாடகை",
                "priceType.SALE" to "விற்பனை விலை",
                "source.AUTO" to "தானாக",
                "source.MANUAL" to "நான் சேர்த்தது",
                "check.water" to "தண்ணீர் வசதி",
                "check.power" to "மின் காப்பு (பவர் பேக்கப்)",
                "check.parking" to "வாகன நிறுத்தம்",
                "check.sunlight" to "சூரிய ஒளி",
                "check.ventilation" to "காற்றோட்டம்",
                "check.noise" to "அமைதி (குறைந்த இரைச்சல்)",
                "check.security" to "பாதுகாப்பு",
                "check.maintenance" to "கட்டிடத்தின் நிலை",
                "check.neighbourhood" to "சுற்றுப்புறம்",
                "check.commute" to "போக்குவரத்து வசதி",
            ),
        )

        val TE = ExportStrings(
            "te",
            mapOf(
                "doc.title" to "Doorprints — నా ఇళ్లు",
                "doc.subtitle" to "నా ఫోన్‌లో సేవ్ చేసిన ప్రతిదాని కాపీ",
                "cover.exported" to "కాపీ తీసిన సమయం",
                "cover.times" to "సమయాలు UTC ప్రకారం",
                "cover.counts" to "ఈ కాపీలో ఏమి ఉంది",
                "cover.houses" to "ఇళ్లు",
                "cover.visits" to "సందర్శనలు",
                "cover.photos" to "ఫోటోలు",
                "cover.options" to "ఎంపికలు",
                "cover.scope" to "చేర్చిన ఇళ్లు",
                "cover.rejected" to "తిరస్కరించిన ఇళ్లు కూడా ఉన్నాయి",
                "cover.photoScope" to "చేర్చిన ఫోటోలు",
                "cover.contacts" to "సంప్రదింపు వివరాలు",
                "cover.language" to "భాష",
                "cover.privacy" to "ఈ కాపీ ఎన్‌క్రిప్ట్ చేయలేదు. ఈ ఫైల్ తెరిచిన ఎవరైనా అందులోని అన్నీ చదవగలరు. సురక్షితమైన చోట ఉంచండి.",
                "cover.contactWarning" to "ఈ కాపీలో యజమానులు, బ్రోకర్ల ఫోన్ నంబర్లు ఉన్నాయి. జాగ్రత్తగా పంచుకోండి.",
                "scope.ALL" to "అన్నీ",
                "scope.SHORTLISTED" to "ఎంపికైనవి మాత్రమే",
                "scope.SELECTED" to "ఎంచుకున్న ఇళ్లు",
                "photoScope.ALL" to "అన్నీ",
                "photoScope.SHORTLISTED" to "ఎంపికైనవి మాత్రమే",
                "photoScope.NONE" to "ఏవీ లేవు",
                "yes" to "అవును",
                "no" to "కాదు",
                "none" to "—",
                "section.ranking" to "మంచివి ముందు",
                "section.details" to "వివరాలు",
                "section.checklist" to "నేను చూసినవి",
                "section.visits" to "సందర్శనలు",
                "section.notes" to "గమనికలు",
                "section.photos" to "ఫోటోలు",
                "section.contact" to "సంప్రదింపు",
                "photos.inBackup" to "ఫోటో ఫైళ్లు ఈ బ్యాకప్‌లోని photos ఫోల్డర్‌లో ఉన్నాయి.",
                "table.houses" to "ఇళ్లు",
                "table.scores" to "స్కోర్లు",
                "table.visits" to "సందర్శనలు",
                "table.photos" to "ఫోటోలు",
                "col.rank" to "వరుస",
                "col.id" to "ఐడీ",
                "col.houseId" to "ఇంటి ఐడీ",
                "col.house" to "ఇల్లు",
                "col.label" to "ఇల్లు",
                "col.status" to "స్థితి",
                "col.score" to "స్కోరు",
                "col.price" to "ధర",
                "col.priceType" to "ధర రకం",
                "col.bedrooms" to "పడకగదులు",
                "col.rating" to "నక్షత్రాలు",
                "col.address" to "చిరునామా",
                "col.street" to "వీధి",
                "col.locality" to "ప్రాంతం",
                "col.lat" to "అక్షాంశం",
                "col.lon" to "రేఖాంశం",
                "col.contactName" to "సంప్రదింపు పేరు",
                "col.contactPhone" to "ఫోన్",
                "col.listingUrl" to "లిస్టింగ్ లింక్",
                "col.notes" to "గమనికలు",
                "col.visits" to "సందర్శనలు",
                "col.photos" to "ఫోటోలు",
                "col.createdAt" to "చేర్చిన తేదీ",
                "col.updatedAt" to "చివరి మార్పు",
                "col.item" to "అంశం కీ",
                "col.itemLabel" to "ఏమిటి",
                "col.arrivedAt" to "చేరిన సమయం",
                "col.leftAt" to "వెళ్లిన సమయం",
                "col.minutes" to "నిమిషాలు",
                "col.source" to "ఎలా నమోదైంది",
                "col.fileName" to "ఫైల్",
                "status.NEW" to "కొత్తది",
                "status.SHORTLISTED" to "ఎంపికైంది",
                "status.REJECTED" to "తిరస్కరించబడింది",
                "priceType.RENT" to "నెలవారీ అద్దె",
                "priceType.SALE" to "అమ్మకం ధర",
                "source.AUTO" to "ఆటోమేటిక్",
                "source.MANUAL" to "నేను చేర్చినది",
                "check.water" to "నీటి సరఫరా",
                "check.power" to "పవర్ బ్యాకప్",
                "check.parking" to "పార్కింగ్",
                "check.sunlight" to "సూర్యరశ్మి",
                "check.ventilation" to "గాలి ప్రసరణ",
                "check.noise" to "ప్రశాంతత (తక్కువ శబ్దం)",
                "check.security" to "భద్రత",
                "check.maintenance" to "భవనం పరిస్థితి",
                "check.neighbourhood" to "పరిసరాలు",
                "check.commute" to "రాకపోకల సౌలభ్యం",
            ),
        )

        /** All four, for the "same keys everywhere" test. */
        val ALL = listOf(EN, HI, TA, TE)
    }
}
