import type { Lang } from '../i18n/languages';

/**
 * The words that appear **inside** an exported table, in the export language.
 *
 * This is the TypeScript half of `android/shared/src/commonMain/kotlin/com/househunt/shared/export/
 * ExportStrings.kt`: the same keys, the same wordings, in the same order. The two files are a contract, like
 * `sync-rules.ts` and `SyncRules.kt`: a change on one side that is not made on the other shows up as a failing
 * golden test rather than as two apps quietly writing different files.
 *
 * Why these are not the app's own i18n catalogue (`i18n/en.ts`), which is the question a reader will have:
 *  * the export language is chosen **per export**, so a copy in Tamil has to be possible while the app itself is
 *    being used in English — `ExportOptions.lang`, not `TranslationService.lang`;
 *  * `commonMain` on the Android side cannot read Android resources, and the same table drives both apps;
 *  * a golden test can only pin the output if the headings are part of the pinned code.
 *
 * `export-strings.spec.ts` checks that all four languages carry exactly these keys.
 */

/** One export language's table of words. Every language has exactly {@link EXPORT_STRING_KEYS}. */
export type ExportDict = Readonly<Record<ExportStringKey, string>>;

/** Every key, in the order `ExportStrings.kt` declares them. */
export const EXPORT_STRING_KEYS = [
  'doc.title',
  'doc.subtitle',
  'cover.exported',
  'cover.times',
  'cover.counts',
  'cover.houses',
  'cover.visits',
  'cover.photos',
  'cover.options',
  'cover.scope',
  'cover.rejected',
  'cover.photoScope',
  'cover.contacts',
  'cover.language',
  'cover.privacy',
  'cover.contactWarning',
  'scope.ALL',
  'scope.SHORTLISTED',
  'scope.SELECTED',
  'photoScope.ALL',
  'photoScope.SHORTLISTED',
  'photoScope.NONE',
  'yes',
  'no',
  'none',
  'section.ranking',
  'section.details',
  'section.checklist',
  'section.visits',
  'section.notes',
  'section.photos',
  'section.contact',
  'photos.inBackup',
  'table.houses',
  'table.scores',
  'table.visits',
  'table.photos',
  'col.rank',
  'col.id',
  'col.houseId',
  'col.house',
  'col.label',
  'col.status',
  'col.score',
  'col.price',
  'col.priceType',
  'col.bedrooms',
  'col.rating',
  'col.address',
  'col.street',
  'col.locality',
  'col.lat',
  'col.lon',
  'col.contactName',
  'col.contactPhone',
  'col.listingUrl',
  'col.notes',
  'col.visits',
  'col.photos',
  'col.createdAt',
  'col.updatedAt',
  'col.item',
  'col.itemLabel',
  'col.arrivedAt',
  'col.leftAt',
  'col.minutes',
  'col.source',
  'col.fileName',
  'status.NEW',
  'status.SHORTLISTED',
  'status.REJECTED',
  'priceType.RENT',
  'priceType.SALE',
  'source.AUTO',
  'source.MANUAL',
  'check.water',
  'check.power',
  'check.parking',
  'check.sunlight',
  'check.ventilation',
  'check.noise',
  'check.security',
  'check.maintenance',
  'check.neighbourhood',
  'check.commute',
] as const;

export type ExportStringKey = (typeof EXPORT_STRING_KEYS)[number];

const EXPORT_EN: ExportDict = {
  'doc.title': 'Doorprints — my houses',
  'doc.subtitle': 'A copy of everything saved on my phone',
  'cover.exported': 'Copy made',
  'cover.times': 'Times shown for UTC',
  'cover.counts': 'What is in this copy',
  'cover.houses': 'Houses',
  'cover.visits': 'Visits',
  'cover.photos': 'Photos',
  'cover.options': 'Options',
  'cover.scope': 'Houses included',
  'cover.rejected': 'Rejected houses included',
  'cover.photoScope': 'Photos included',
  'cover.contacts': 'Contact details',
  'cover.language': 'Language',
  'cover.privacy': 'This copy is not encrypted. Anyone who opens the file can read everything in it. Keep it somewhere safe.',
  'cover.contactWarning': 'This copy contains phone numbers of owners and brokers. Share it carefully.',
  'scope.ALL': 'All',
  'scope.SHORTLISTED': 'Shortlisted only',
  'scope.SELECTED': 'Selected houses',
  'photoScope.ALL': 'All',
  'photoScope.SHORTLISTED': 'Shortlisted only',
  'photoScope.NONE': 'None',
  'yes': 'Yes',
  'no': 'No',
  'none': '—',
  'section.ranking': 'Best first',
  'section.details': 'Details',
  'section.checklist': 'What I checked',
  'section.visits': 'Visits',
  'section.notes': 'Notes',
  'section.photos': 'Photos',
  'section.contact': 'Contact',
  'photos.inBackup': 'The photo files are in the photos folder of this backup.',
  'table.houses': 'Houses',
  'table.scores': 'Scores',
  'table.visits': 'Visits',
  'table.photos': 'Photos',
  'col.rank': 'Rank',
  'col.id': 'Id',
  'col.houseId': 'House id',
  'col.house': 'House',
  'col.label': 'House',
  'col.status': 'Status',
  'col.score': 'Score',
  'col.price': 'Price',
  'col.priceType': 'Price type',
  'col.bedrooms': 'Bedrooms',
  'col.rating': 'Stars',
  'col.address': 'Address',
  'col.street': 'Street',
  'col.locality': 'Locality',
  'col.lat': 'Latitude',
  'col.lon': 'Longitude',
  'col.contactName': 'Contact name',
  'col.contactPhone': 'Phone',
  'col.listingUrl': 'Listing link',
  'col.notes': 'Notes',
  'col.visits': 'Visits',
  'col.photos': 'Photos',
  'col.createdAt': 'Added',
  'col.updatedAt': 'Last changed',
  'col.item': 'Item key',
  'col.itemLabel': 'What',
  'col.arrivedAt': 'Arrived',
  'col.leftAt': 'Left',
  'col.minutes': 'Minutes',
  'col.source': 'How recorded',
  'col.fileName': 'File',
  'status.NEW': 'New',
  'status.SHORTLISTED': 'Shortlisted',
  'status.REJECTED': 'Rejected',
  'priceType.RENT': 'Rent per month',
  'priceType.SALE': 'Sale price',
  'source.AUTO': 'Automatic',
  'source.MANUAL': 'Added by me',
  'check.water': 'Water supply',
  'check.power': 'Power backup',
  'check.parking': 'Parking',
  'check.sunlight': 'Sunlight',
  'check.ventilation': 'Ventilation',
  'check.noise': 'Quiet (low noise)',
  'check.security': 'Safety and security',
  'check.maintenance': 'Building condition',
  'check.neighbourhood': 'Neighbourhood',
  'check.commute': 'Commute',
};

const EXPORT_HI: ExportDict = {
  'doc.title': 'Doorprints — मेरे मकान',
  'doc.subtitle': 'मेरे फ़ोन में सहेजी हर चीज़ की एक प्रति',
  'cover.exported': 'प्रति बनाई गई',
  'cover.times': 'समय UTC के अनुसार',
  'cover.counts': 'इस प्रति में क्या है',
  'cover.houses': 'मकान',
  'cover.visits': 'दौरे',
  'cover.photos': 'तस्वीरें',
  'cover.options': 'विकल्प',
  'cover.scope': 'शामिल मकान',
  'cover.rejected': 'अस्वीकृत मकान शामिल',
  'cover.photoScope': 'शामिल तस्वीरें',
  'cover.contacts': 'संपर्क विवरण',
  'cover.language': 'भाषा',
  'cover.privacy': 'यह प्रति एन्क्रिप्ट नहीं है। जो भी इस फ़ाइल को खोलेगा वह सब कुछ पढ़ सकता है। इसे सुरक्षित जगह रखें।',
  'cover.contactWarning': 'इस प्रति में मालिकों और दलालों के फ़ोन नंबर हैं। इसे सोच-समझकर साझा करें।',
  'scope.ALL': 'सभी',
  'scope.SHORTLISTED': 'केवल चुने गए',
  'scope.SELECTED': 'चयनित मकान',
  'photoScope.ALL': 'सभी',
  'photoScope.SHORTLISTED': 'केवल चुने गए',
  'photoScope.NONE': 'कोई नहीं',
  'yes': 'हाँ',
  'no': 'नहीं',
  'none': '—',
  'section.ranking': 'सबसे अच्छे पहले',
  'section.details': 'विवरण',
  'section.checklist': 'मैंने क्या जाँचा',
  'section.visits': 'दौरे',
  'section.notes': 'नोट',
  'section.photos': 'तस्वीरें',
  'section.contact': 'संपर्क',
  'photos.inBackup': 'तस्वीरों की फ़ाइलें इस बैकअप के photos फ़ोल्डर में हैं।',
  'table.houses': 'मकान',
  'table.scores': 'अंक',
  'table.visits': 'दौरे',
  'table.photos': 'तस्वीरें',
  'col.rank': 'क्रम',
  'col.id': 'आईडी',
  'col.houseId': 'मकान आईडी',
  'col.house': 'मकान',
  'col.label': 'मकान',
  'col.status': 'स्थिति',
  'col.score': 'अंक',
  'col.price': 'कीमत',
  'col.priceType': 'कीमत का प्रकार',
  'col.bedrooms': 'बेडरूम',
  'col.rating': 'सितारे',
  'col.address': 'पता',
  'col.street': 'सड़क',
  'col.locality': 'इलाका',
  'col.lat': 'अक्षांश',
  'col.lon': 'देशांतर',
  'col.contactName': 'संपर्क नाम',
  'col.contactPhone': 'फ़ोन',
  'col.listingUrl': 'लिस्टिंग लिंक',
  'col.notes': 'नोट',
  'col.visits': 'दौरे',
  'col.photos': 'तस्वीरें',
  'col.createdAt': 'जोड़ा गया',
  'col.updatedAt': 'आख़िरी बदलाव',
  'col.item': 'आइटम की',
  'col.itemLabel': 'क्या',
  'col.arrivedAt': 'पहुँचे',
  'col.leftAt': 'निकले',
  'col.minutes': 'मिनट',
  'col.source': 'कैसे दर्ज हुआ',
  'col.fileName': 'फ़ाइल',
  'status.NEW': 'नया',
  'status.SHORTLISTED': 'चुना गया',
  'status.REJECTED': 'अस्वीकृत',
  'priceType.RENT': 'किराया प्रति माह',
  'priceType.SALE': 'बिक्री कीमत',
  'source.AUTO': 'अपने आप',
  'source.MANUAL': 'मैंने जोड़ा',
  'check.water': 'पानी की आपूर्ति',
  'check.power': 'बिजली बैकअप',
  'check.parking': 'पार्किंग',
  'check.sunlight': 'धूप',
  'check.ventilation': 'हवादारी',
  'check.noise': 'शांति (कम शोर)',
  'check.security': 'सुरक्षा',
  'check.maintenance': 'इमारत की हालत',
  'check.neighbourhood': 'आस-पड़ोस',
  'check.commute': 'आने-जाने की सुविधा',
};

const EXPORT_TA: ExportDict = {
  'doc.title': 'Doorprints — என் வீடுகள்',
  'doc.subtitle': 'என் தொலைபேசியில் சேமித்த அனைத்தின் நகல்',
  'cover.exported': 'நகல் எடுக்கப்பட்டது',
  'cover.times': 'நேரங்கள் UTC அடிப்படையில்',
  'cover.counts': 'இந்த நகலில் உள்ளவை',
  'cover.houses': 'வீடுகள்',
  'cover.visits': 'வருகைகள்',
  'cover.photos': 'படங்கள்',
  'cover.options': 'விருப்பங்கள்',
  'cover.scope': 'சேர்க்கப்பட்ட வீடுகள்',
  'cover.rejected': 'நிராகரிக்கப்பட்ட வீடுகளும் உள்ளன',
  'cover.photoScope': 'சேர்க்கப்பட்ட படங்கள்',
  'cover.contacts': 'தொடர்பு விவரங்கள்',
  'cover.language': 'மொழி',
  'cover.privacy': 'இந்த நகல் மறையாக்கம் செய்யப்படவில்லை. இந்தக் கோப்பைத் திறக்கும் எவரும் எல்லாவற்றையும் படிக்க முடியும். பாதுகாப்பான இடத்தில் வைக்கவும்.',
  'cover.contactWarning': 'இந்த நகலில் உரிமையாளர்கள் மற்றும் தரகர்களின் தொலைபேசி எண்கள் உள்ளன. கவனமாகப் பகிரவும்.',
  'scope.ALL': 'அனைத்தும்',
  'scope.SHORTLISTED': 'தேர்வானவை மட்டும்',
  'scope.SELECTED': 'தேர்ந்தெடுத்த வீடுகள்',
  'photoScope.ALL': 'அனைத்தும்',
  'photoScope.SHORTLISTED': 'தேர்வானவை மட்டும்',
  'photoScope.NONE': 'எதுவும் இல்லை',
  'yes': 'ஆம்',
  'no': 'இல்லை',
  'none': '—',
  'section.ranking': 'சிறந்தவை முதலில்',
  'section.details': 'விவரங்கள்',
  'section.checklist': 'நான் சரிபார்த்தவை',
  'section.visits': 'வருகைகள்',
  'section.notes': 'குறிப்புகள்',
  'section.photos': 'படங்கள்',
  'section.contact': 'தொடர்பு',
  'photos.inBackup': 'படக் கோப்புகள் இந்த காப்புப்பிரதியின் photos கோப்புறையில் உள்ளன.',
  'table.houses': 'வீடுகள்',
  'table.scores': 'மதிப்பெண்கள்',
  'table.visits': 'வருகைகள்',
  'table.photos': 'படங்கள்',
  'col.rank': 'வரிசை',
  'col.id': 'அடையாளம்',
  'col.houseId': 'வீட்டு அடையாளம்',
  'col.house': 'வீடு',
  'col.label': 'வீடு',
  'col.status': 'நிலை',
  'col.score': 'மதிப்பெண்',
  'col.price': 'விலை',
  'col.priceType': 'விலை வகை',
  'col.bedrooms': 'படுக்கையறைகள்',
  'col.rating': 'நட்சத்திரங்கள்',
  'col.address': 'முகவரி',
  'col.street': 'தெரு',
  'col.locality': 'பகுதி',
  'col.lat': 'அட்சரேகை',
  'col.lon': 'தீர்க்கரேகை',
  'col.contactName': 'தொடர்பு பெயர்',
  'col.contactPhone': 'தொலைபேசி',
  'col.listingUrl': 'விளம்பர இணைப்பு',
  'col.notes': 'குறிப்புகள்',
  'col.visits': 'வருகைகள்',
  'col.photos': 'படங்கள்',
  'col.createdAt': 'சேர்க்கப்பட்டது',
  'col.updatedAt': 'கடைசி மாற்றம்',
  'col.item': 'உருப்படிக் குறியீடு',
  'col.itemLabel': 'என்ன',
  'col.arrivedAt': 'வந்த நேரம்',
  'col.leftAt': 'சென்ற நேரம்',
  'col.minutes': 'நிமிடங்கள்',
  'col.source': 'எப்படிப் பதிவானது',
  'col.fileName': 'கோப்பு',
  'status.NEW': 'புதியது',
  'status.SHORTLISTED': 'தேர்வானது',
  'status.REJECTED': 'நிராகரிக்கப்பட்டது',
  'priceType.RENT': 'மாத வாடகை',
  'priceType.SALE': 'விற்பனை விலை',
  'source.AUTO': 'தானாக',
  'source.MANUAL': 'நான் சேர்த்தது',
  'check.water': 'தண்ணீர் வசதி',
  'check.power': 'மின் காப்பு (பவர் பேக்கப்)',
  'check.parking': 'வாகன நிறுத்தம்',
  'check.sunlight': 'சூரிய ஒளி',
  'check.ventilation': 'காற்றோட்டம்',
  'check.noise': 'அமைதி (குறைந்த இரைச்சல்)',
  'check.security': 'பாதுகாப்பு',
  'check.maintenance': 'கட்டிடத்தின் நிலை',
  'check.neighbourhood': 'சுற்றுப்புறம்',
  'check.commute': 'போக்குவரத்து வசதி',
};

const EXPORT_TE: ExportDict = {
  'doc.title': 'Doorprints — నా ఇళ్లు',
  'doc.subtitle': 'నా ఫోన్‌లో సేవ్ చేసిన ప్రతిదాని కాపీ',
  'cover.exported': 'కాపీ తీసిన సమయం',
  'cover.times': 'సమయాలు UTC ప్రకారం',
  'cover.counts': 'ఈ కాపీలో ఏమి ఉంది',
  'cover.houses': 'ఇళ్లు',
  'cover.visits': 'సందర్శనలు',
  'cover.photos': 'ఫోటోలు',
  'cover.options': 'ఎంపికలు',
  'cover.scope': 'చేర్చిన ఇళ్లు',
  'cover.rejected': 'తిరస్కరించిన ఇళ్లు కూడా ఉన్నాయి',
  'cover.photoScope': 'చేర్చిన ఫోటోలు',
  'cover.contacts': 'సంప్రదింపు వివరాలు',
  'cover.language': 'భాష',
  'cover.privacy': 'ఈ కాపీ ఎన్‌క్రిప్ట్ చేయలేదు. ఈ ఫైల్ తెరిచిన ఎవరైనా అందులోని అన్నీ చదవగలరు. సురక్షితమైన చోట ఉంచండి.',
  'cover.contactWarning': 'ఈ కాపీలో యజమానులు, బ్రోకర్ల ఫోన్ నంబర్లు ఉన్నాయి. జాగ్రత్తగా పంచుకోండి.',
  'scope.ALL': 'అన్నీ',
  'scope.SHORTLISTED': 'ఎంపికైనవి మాత్రమే',
  'scope.SELECTED': 'ఎంచుకున్న ఇళ్లు',
  'photoScope.ALL': 'అన్నీ',
  'photoScope.SHORTLISTED': 'ఎంపికైనవి మాత్రమే',
  'photoScope.NONE': 'ఏవీ లేవు',
  'yes': 'అవును',
  'no': 'కాదు',
  'none': '—',
  'section.ranking': 'మంచివి ముందు',
  'section.details': 'వివరాలు',
  'section.checklist': 'నేను చూసినవి',
  'section.visits': 'సందర్శనలు',
  'section.notes': 'గమనికలు',
  'section.photos': 'ఫోటోలు',
  'section.contact': 'సంప్రదింపు',
  'photos.inBackup': 'ఫోటో ఫైళ్లు ఈ బ్యాకప్‌లోని photos ఫోల్డర్‌లో ఉన్నాయి.',
  'table.houses': 'ఇళ్లు',
  'table.scores': 'స్కోర్లు',
  'table.visits': 'సందర్శనలు',
  'table.photos': 'ఫోటోలు',
  'col.rank': 'వరుస',
  'col.id': 'ఐడీ',
  'col.houseId': 'ఇంటి ఐడీ',
  'col.house': 'ఇల్లు',
  'col.label': 'ఇల్లు',
  'col.status': 'స్థితి',
  'col.score': 'స్కోరు',
  'col.price': 'ధర',
  'col.priceType': 'ధర రకం',
  'col.bedrooms': 'పడకగదులు',
  'col.rating': 'నక్షత్రాలు',
  'col.address': 'చిరునామా',
  'col.street': 'వీధి',
  'col.locality': 'ప్రాంతం',
  'col.lat': 'అక్షాంశం',
  'col.lon': 'రేఖాంశం',
  'col.contactName': 'సంప్రదింపు పేరు',
  'col.contactPhone': 'ఫోన్',
  'col.listingUrl': 'లిస్టింగ్ లింక్',
  'col.notes': 'గమనికలు',
  'col.visits': 'సందర్శనలు',
  'col.photos': 'ఫోటోలు',
  'col.createdAt': 'చేర్చిన తేదీ',
  'col.updatedAt': 'చివరి మార్పు',
  'col.item': 'అంశం కీ',
  'col.itemLabel': 'ఏమిటి',
  'col.arrivedAt': 'చేరిన సమయం',
  'col.leftAt': 'వెళ్లిన సమయం',
  'col.minutes': 'నిమిషాలు',
  'col.source': 'ఎలా నమోదైంది',
  'col.fileName': 'ఫైల్',
  'status.NEW': 'కొత్తది',
  'status.SHORTLISTED': 'ఎంపికైంది',
  'status.REJECTED': 'తిరస్కరించబడింది',
  'priceType.RENT': 'నెలవారీ అద్దె',
  'priceType.SALE': 'అమ్మకం ధర',
  'source.AUTO': 'ఆటోమేటిక్',
  'source.MANUAL': 'నేను చేర్చినది',
  'check.water': 'నీటి సరఫరా',
  'check.power': 'పవర్ బ్యాకప్',
  'check.parking': 'పార్కింగ్',
  'check.sunlight': 'సూర్యరశ్మి',
  'check.ventilation': 'గాలి ప్రసరణ',
  'check.noise': 'ప్రశాంతత (తక్కువ శబ్దం)',
  'check.security': 'భద్రత',
  'check.maintenance': 'భవనం పరిస్థితి',
  'check.neighbourhood': 'పరిసరాలు',
  'check.commute': 'రాకపోకల సౌలభ్యం',
};

const EXPORT_DICTS: Readonly<Record<Lang, ExportDict>> = {
  en: EXPORT_EN,
  hi: EXPORT_HI,
  ta: EXPORT_TA,
  te: EXPORT_TE,
};

/**
 * Reader for one export language. `get` throws on an unknown key, because that is a programming error rather
 * than user input; the `status` / `source` / `priceType` / `check` lookups fall back to the raw key, because
 * those come from stored data a newer app version may have written (a custom checklist criterion, Sprint 4b).
 */
export class ExportStrings {
  readonly language: Lang;
  private readonly values: ExportDict;

  private constructor(language: Lang, values: ExportDict) {
    this.language = language;
    this.values = values;
  }

  static of(language: Lang): ExportStrings {
    return new ExportStrings(language, EXPORT_DICTS[language] ?? EXPORT_EN);
  }

  get(key: ExportStringKey): string {
    const value = this.values[key];
    if (value === undefined) throw new Error(`No export string '${key}' for '${this.language}'`);
    return value;
  }

  /** Translated label of a checklist key; the key itself when this version does not know it. */
  check(key: string): string {
    return this.lookup(`check.${key}`) ?? key;
  }

  status(name: string): string {
    return this.lookup(`status.${name}`) ?? name;
  }

  source(name: string): string {
    return this.lookup(`source.${name}`) ?? name;
  }

  priceType(name: string | null | undefined): string {
    return this.lookup(`priceType.${name ?? 'RENT'}`) ?? name ?? '';
  }

  private lookup(key: string): string | undefined {
    return (this.values as Readonly<Record<string, string>>)[key];
  }
}

export const ALL_EXPORT_STRINGS: readonly ExportStrings[] = (['en', 'hi', 'ta', 'te'] as const).map((l) =>
  ExportStrings.of(l),
);
